My Project: src/c/ssht_adjoint.c File Reference
ssht_adjoint.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <complex.h>
#include <fftw3.h>
#include "ssht_types.h"
#include "ssht_error.h"
#include "ssht_dl.h"
#include "ssht_sampling.h"
#include "ssht_adjoint.h"
Functions
void ssht_adjoint_mw_inverse_sov_sym (SSHT_COMPLEX(double) *flm, const SSHT_COMPLEX(double) *f, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_inverse_sov_sym_real (SSHT_COMPLEX(double) *flm, const double *f, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_forward_sov_sym (SSHT_COMPLEX(double) *f, const SSHT_COMPLEX(double) *flm, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_forward_sov_sym_real (double *f, const SSHT_COMPLEX(double) *flm, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_forward_sov_sym_pole (SSHT_COMPLEX(double) *f, SSHT_COMPLEX(double) *f_sp, double *phi_sp, SSHT_COMPLEX(double) *flm, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_forward_sov_sym_real_pole (double *f, double *f_sp, SSHT_COMPLEX(double) *flm, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_inverse_sov_sym_pole (SSHT_COMPLEX(double) *flm, SSHT_COMPLEX(double) *f, SSHT_COMPLEX(double) f_sp, double phi_sp, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_inverse_sov_sym_real_pole (SSHT_COMPLEX(double) *flm, double *f, double f_sp, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_inverse_sov_sym_ss (SSHT_COMPLEX(double) *flm, SSHT_COMPLEX(double) *f, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_inverse_sov_sym_ss_real (SSHT_COMPLEX(double) *flm, double *f, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_forward_sov_sym_ss (SSHT_COMPLEX(double) *f, SSHT_COMPLEX(double) *flm, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_forward_sov_sym_ss_real (double *f, SSHT_COMPLEX(double) *flm, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_forward_sov_sym_ss_pole (SSHT_COMPLEX(double) *f, SSHT_COMPLEX(double) *f_np, double *phi_np, SSHT_COMPLEX(double) *f_sp, double *phi_sp, SSHT_COMPLEX(double) *flm, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_forward_sov_sym_ss_real_pole (double *f, double *f_np, double *f_sp, SSHT_COMPLEX(double) *flm, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_inverse_sov_sym_ss_pole (SSHT_COMPLEX(double) *flm, SSHT_COMPLEX(double) *f, SSHT_COMPLEX(double) f_np, double phi_np, SSHT_COMPLEX(double) f_sp, double phi_sp, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_inverse_sov_sym_ss_real_pole (SSHT_COMPLEX(double) *flm, double *f, double f_np, double f_sp, int L, ssht_dl_method_t dl_method, int verbosity)
Detailed Description
Algorithms to perform fast adjoint of spin spherical harmonic transforms on the sphere.
Author
Jason McEwen
Definition in file ssht_adjoint.c.
Function Documentation
ssht_adjoint_mw_forward_sov_sym()
void ssht_adjoint_mw_forward_sov_sym (SSHT_COMPLEX(double) * f, const SSHT_COMPLEX(double) * flm, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
Compute adjoint of forward transform for MW method using separation of variables, fast Fourier transforms, performing convolution with weights as product in transformed space and exploiting all symmetries (for complex spin signal).
Parameters
[out] f Function on sphere.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 597 of file ssht_adjoint.c.
References SSHT_COMPLEX, ssht_dl_beta_risbo_eighth_table(), ssht_dl_beta_risbo_fill_eighth2quarter_table(), ssht_dl_calloc(), ssht_dl_get_offset(), ssht_dl_get_stride(), ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), SSHT_DL_QUARTER, SSHT_DL_QUARTER_EXTENDED, SSHT_DL_RISBO, SSHT_DL_TRAPANI, SSHT_ERROR_GENERIC, SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PION2, and SSHT_PROMPT.
Referenced by ssht_adjoint_mw_forward_sov_sym_pole().
ssht_adjoint_mw_forward_sov_sym_pole()
void ssht_adjoint_mw_forward_sov_sym_pole (SSHT_COMPLEX(double) * f, SSHT_COMPLEX(double) * f_sp, double * phi_sp, SSHT_COMPLEX(double) * flm, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
South pole wrapper for adjoint forward transform for MW method. The South pole is defined by a single sample and its corresponding phi angle, rather than specifying samples for all phi at the South pole (which are simply related by the rotation of a spin function in its tangent plane).
Parameters
[out] f Function on sphere (excluding South pole).
[out] f_sp Function sample on South pole.
[out] phi_sp Phi angle corresponding to quoted sample at South pole.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 1304 of file ssht_adjoint.c.
References ssht_adjoint_mw_forward_sov_sym(), SSHT_COMPLEX, SSHT_ERROR_MEM_ALLOC_CHECK, and ssht_sampling_mw_p2phi().
ssht_adjoint_mw_forward_sov_sym_real()
void ssht_adjoint_mw_forward_sov_sym_real (double * f, const SSHT_COMPLEX(double) * flm, int L, ssht_dl_method_t dl_method, int verbosity)
Compute adjoint of forward transform for MW method of real scalar signal using separation of variables, fast Fourier transforms, performing convolution with weights as product in transformed space and exploiting all symmetries (including additional symmetries for real signals).
Parameters
[out] f Function on sphere.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 946 of file ssht_adjoint.c.
References SSHT_COMPLEX, ssht_dl_beta_risbo_eighth_table(), ssht_dl_beta_risbo_fill_eighth2quarter_table(), ssht_dl_calloc(), ssht_dl_get_offset(), ssht_dl_get_stride(), ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), SSHT_DL_QUARTER, SSHT_DL_QUARTER_EXTENDED, SSHT_DL_RISBO, SSHT_DL_TRAPANI, SSHT_ERROR_GENERIC, SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PION2, and SSHT_PROMPT.
Referenced by ssht_adjoint_mw_forward_sov_sym_real_pole().
ssht_adjoint_mw_forward_sov_sym_real_pole()
void ssht_adjoint_mw_forward_sov_sym_real_pole (double * f, double * f_sp, SSHT_COMPLEX(double) * flm, int L, ssht_dl_method_t dl_method, int verbosity)
South pole wrapper for adjoint forward transform of real scalar function for MW method. The South pole is defined by a single sample, rather than specifying samples for all phi at the South pole (which for a scalar function are identical).
Parameters
[out] f Function on sphere (excluding South pole).
[out] f_sp Function sample on South pole.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 1350 of file ssht_adjoint.c.
References ssht_adjoint_mw_forward_sov_sym_real(), and SSHT_ERROR_MEM_ALLOC_CHECK.
ssht_adjoint_mw_forward_sov_sym_ss()
void ssht_adjoint_mw_forward_sov_sym_ss (SSHT_COMPLEX(double) * f, SSHT_COMPLEX(double) * flm, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
Compute adjoint of forward transform for MW method with symmetric sampling using separation of variables, fast Fourier transforms, performing convolution with weights as product in transformed space and exploiting all symmetries (for complex spin signal).
Parameters
[out] f Function on sphere.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 2034 of file ssht_adjoint.c.
References SSHT_COMPLEX, ssht_dl_beta_risbo_eighth_table(), ssht_dl_beta_risbo_fill_eighth2quarter_table(), ssht_dl_calloc(), ssht_dl_get_offset(), ssht_dl_get_stride(), ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), SSHT_DL_QUARTER, SSHT_DL_QUARTER_EXTENDED, SSHT_DL_RISBO, SSHT_DL_TRAPANI, SSHT_ERROR_GENERIC, SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PION2, and SSHT_PROMPT.
Referenced by ssht_adjoint_mw_forward_sov_sym_ss_pole().
ssht_adjoint_mw_forward_sov_sym_ss_pole()
void ssht_adjoint_mw_forward_sov_sym_ss_pole (SSHT_COMPLEX(double) * f, SSHT_COMPLEX(double) * f_np, double * phi_np, SSHT_COMPLEX(double) * f_sp, double * phi_sp, SSHT_COMPLEX(double) * flm, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
North-South pole wrapper for adjoint forward transform for MW method with symmetric sampling. The poles are defined by single samples and their corresponding phi angle, rather than specifying samples for all phi at the poles (which are simply related by the rotation of a spin function in its tangent plane).
Parameters
[out] f Function on sphere (excluding poles).
[out] f_np Function sample on North pole.
[out] phi_np Phi angle corresponding to quoted sample at North pole.
[out] f_sp Function sample on South pole.
[out] phi_sp Phi angle corresponding to quoted sample at South pole.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 2731 of file ssht_adjoint.c.
References ssht_adjoint_mw_forward_sov_sym_ss(), SSHT_COMPLEX, SSHT_ERROR_MEM_ALLOC_CHECK, and ssht_sampling_mw_ss_p2phi().
ssht_adjoint_mw_forward_sov_sym_ss_real()
void ssht_adjoint_mw_forward_sov_sym_ss_real (double * f, SSHT_COMPLEX(double) * flm, int L, ssht_dl_method_t dl_method, int verbosity)
Compute adjoint of forward transform for MW method with symmetric sampling of real scalar signal using separation of variables, fast Fourier transforms, performing convolution with weights as product in transformed space and exploiting all symmetries (including additional symmetries for real signals).
Parameters
[out] f Function on sphere.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 2378 of file ssht_adjoint.c.
References SSHT_COMPLEX, ssht_dl_beta_risbo_eighth_table(), ssht_dl_beta_risbo_fill_eighth2quarter_table(), ssht_dl_calloc(), ssht_dl_get_offset(), ssht_dl_get_stride(), ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), SSHT_DL_QUARTER, SSHT_DL_QUARTER_EXTENDED, SSHT_DL_RISBO, SSHT_DL_TRAPANI, SSHT_ERROR_GENERIC, SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PION2, and SSHT_PROMPT.
Referenced by ssht_adjoint_mw_forward_sov_sym_ss_real_pole().
ssht_adjoint_mw_forward_sov_sym_ss_real_pole()
void ssht_adjoint_mw_forward_sov_sym_ss_real_pole (double * f, double * f_np, double * f_sp, SSHT_COMPLEX(double) * flm, int L, ssht_dl_method_t dl_method, int verbosity)
North-South pole wrapper for adjoint forward transform of real scalar function for MW method with symmetric sampling. The poles are defined by single samples, rather than specifying samples for all phi at the poles (which for a scalar function are identical).
Parameters
[out] f Function on sphere (excluding poles).
[out] f_sp Function sample on South pole.
[out] f_np Function sample on North pole.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 2783 of file ssht_adjoint.c.
References ssht_adjoint_mw_forward_sov_sym_ss_real(), and SSHT_ERROR_MEM_ALLOC_CHECK.
ssht_adjoint_mw_inverse_sov_sym()
void ssht_adjoint_mw_inverse_sov_sym (SSHT_COMPLEX(double) * flm, const SSHT_COMPLEX(double) * f, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
Compute adjoint of inverse transform for MW method using separation of variables, fast Fourier transforms and exploiting all symmetries (for complex spin signal).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 48 of file ssht_adjoint.c.
References SSHT_COMPLEX, ssht_dl_calloc(), ssht_dl_get_offset(), ssht_dl_get_stride(), SSHT_DL_QUARTER, SSHT_DL_QUARTER_EXTENDED, SSHT_DL_RISBO, SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PION2, and SSHT_PROMPT.
Referenced by ssht_adjoint_mw_inverse_sov_sym_pole().
ssht_adjoint_mw_inverse_sov_sym_pole()
void ssht_adjoint_mw_inverse_sov_sym_pole (SSHT_COMPLEX(double) * flm, SSHT_COMPLEX(double) * f, SSHT_COMPLEX(double) f_sp, double phi_sp, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
South pole wrapper for adjoint inverse transform for MW method. The South pole is defined by a single sample and its corresponding phi angle, rather than specifying samples for all phi at the South pole (which are simply related by the rotation of a spin function in its tangent plane).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere (excluding South pole).
[in] f_sp Function sample on South pole.
[in] phi_sp Phi angle corresponding to quoted sample at South pole.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 1398 of file ssht_adjoint.c.
References ssht_adjoint_mw_inverse_sov_sym(), SSHT_COMPLEX, SSHT_ERROR_MEM_ALLOC_CHECK, and ssht_sampling_mw_p2phi().
ssht_adjoint_mw_inverse_sov_sym_real()
void ssht_adjoint_mw_inverse_sov_sym_real (SSHT_COMPLEX(double) * flm, const double * f, int L, ssht_dl_method_t dl_method, int verbosity)
Compute adjoint of inverse transform for MW method of real scalar signal using separation of variables, fast Fourier transforms and exploiting all symmetries (including additional symmetries for real signals).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere.
[in] L Harmonic band-limit.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 325 of file ssht_adjoint.c.
References SSHT_COMPLEX, ssht_dl_calloc(), ssht_dl_get_offset(), ssht_dl_get_stride(), SSHT_DL_QUARTER, SSHT_DL_QUARTER_EXTENDED, SSHT_DL_RISBO, SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PION2, and SSHT_PROMPT.
Referenced by ssht_adjoint_mw_inverse_sov_sym_real_pole().
ssht_adjoint_mw_inverse_sov_sym_real_pole()
void ssht_adjoint_mw_inverse_sov_sym_real_pole (SSHT_COMPLEX(double) * flm, double * f, double f_sp, int L, ssht_dl_method_t dl_method, int verbosity)
South pole wrapper for adjoint inverse transform of real scalar function for MW method. The South pole is defined by a single sample, rather than specifying samples for all phi at the South pole (which for a scalar function are identical).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere (excluding South pole).
[in] f_sp Function sample on South pole.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 1446 of file ssht_adjoint.c.
References ssht_adjoint_mw_inverse_sov_sym_real(), and SSHT_ERROR_MEM_ALLOC_CHECK.
ssht_adjoint_mw_inverse_sov_sym_ss()
void ssht_adjoint_mw_inverse_sov_sym_ss (SSHT_COMPLEX(double) * flm, SSHT_COMPLEX(double) * f, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
Compute adjoint of inverse transform for MW method with symmetric sampling using separation of variables, fast Fourier transforms and exploiting all symmetries (for complex spin signal).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 1495 of file ssht_adjoint.c.
References SSHT_COMPLEX, ssht_dl_calloc(), ssht_dl_get_offset(), ssht_dl_get_stride(), SSHT_DL_QUARTER, SSHT_DL_QUARTER_EXTENDED, SSHT_DL_RISBO, SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PION2, and SSHT_PROMPT.
Referenced by ssht_adjoint_mw_inverse_sov_sym_ss_pole().
ssht_adjoint_mw_inverse_sov_sym_ss_pole()
void ssht_adjoint_mw_inverse_sov_sym_ss_pole (SSHT_COMPLEX(double) * flm, SSHT_COMPLEX(double) * f, SSHT_COMPLEX(double) f_np, double phi_np, SSHT_COMPLEX(double) f_sp, double phi_sp, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
North-South pole wrapper for adjoint inverse transform for MW method with symmetric sampling. The poles are defined by single samples and their corresponding phi angle, rather than specifying samples for all phi at the poles (which are simply related by the rotation of a spin function in its tangent plane).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere (excluding poles).
[in] f_np Function sample on North pole.
[in] phi_np Phi angle corresponding to quoted sample at North pole.
[in] f_sp Function sample on South pole.
[in] phi_sp Phi angle corresponding to quoted sample at South pole.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 2838 of file ssht_adjoint.c.
References ssht_adjoint_mw_inverse_sov_sym_ss(), SSHT_COMPLEX, SSHT_ERROR_MEM_ALLOC_CHECK, and ssht_sampling_mw_ss_p2phi().
ssht_adjoint_mw_inverse_sov_sym_ss_real()
void ssht_adjoint_mw_inverse_sov_sym_ss_real (SSHT_COMPLEX(double) * flm, double * f, int L, ssht_dl_method_t dl_method, int verbosity)
Compute adjoint of inverse transform for MW method with symmetric sampling of real scalar signal using separation of variables, fast Fourier transforms and exploiting all symmetries (including additional symmetries for real signals).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere.
[in] L Harmonic band-limit.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 1773 of file ssht_adjoint.c.
References SSHT_COMPLEX, ssht_dl_calloc(), ssht_dl_get_offset(), ssht_dl_get_stride(), SSHT_DL_QUARTER, SSHT_DL_QUARTER_EXTENDED, SSHT_DL_RISBO, SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PION2, and SSHT_PROMPT.
Referenced by ssht_adjoint_mw_inverse_sov_sym_ss_real_pole().
ssht_adjoint_mw_inverse_sov_sym_ss_real_pole()
void ssht_adjoint_mw_inverse_sov_sym_ss_real_pole (SSHT_COMPLEX(double) * flm, double * f, double f_np, double f_sp, int L, ssht_dl_method_t dl_method, int verbosity)
North-South pole wrapper for adjoint inverse transform of real scalar function for MW method with symmetric sampling. The poles are defined by single samples, rather than specifying samples for all phi at the poles (which for a scalar function are identical).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere (excluding poles).
[in] f_np Function sample on North pole.
[in] f_sp Function sample on South pole.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 2891 of file ssht_adjoint.c.
References ssht_adjoint_mw_inverse_sov_sym_ss_real(), and SSHT_ERROR_MEM_ALLOC_CHECK.