#!/bin/sh

bin/ssht_test 256 0 > test_L256_s0.txt
bin/ssht_test 128 0 > test_L128_s0.txt
bin/ssht_test 64 0 > test_L064_s0.txt

bin/ssht_test 256 2 > test_L256_s2.txt
bin/ssht_test 128 2 > test_L128_s2.txt
bin/ssht_test 64 2 > test_L064_s2.txt
