#!/bin/sh

#./bin/c/ssht_test 16 0 > test_L0016_s00.txt
#./bin/c/ssht_test 32 0 > test_L0032_s00.txt
#./bin/c/ssht_test 64 0 > test_L0064_s00.txt
#./bin/c/ssht_test 128 0 > test_L0128_s00.txt
#./bin/c/ssht_test 256 0 > test_L0256_s00.txt
#./bin/c/ssht_test 512 0 > test_L0512_s00.txt
#./bin/c/ssht_test 1024 0 > test_L1024_s00.txt

./bin/c/ssht_test 16 2 > test_L0016_s02.txt
./bin/c/ssht_test 32 2 > test_L0032_s02.txt
./bin/c/ssht_test 64 2 > test_L0064_s02.txt
./bin/c/ssht_test 128 2 > test_L0128_s02.txt
./bin/c/ssht_test 256 2 > test_L0256_s02.txt
./bin/c/ssht_test 512 2 > test_L0512_s02.txt
./bin/c/ssht_test 1024 2 > test_L1024_s02.txt

#./bin/c/ssht_test 2048 0 > test_L2048_s00.txt
#./bin/c/ssht_test 2048 2 > test_L2048_s02.txt

#./bin/c/ssht_test 4096 0 > test_L4096_s00.txt
#./bin/c/ssht_test 4096 2 > test_L4096_s02.txt