ssht_test__interface Interface Reference
ssht_test__interface Interface Reference
Public Member Functions
subroutine ssht_test_gen_flm_real (L, flm, seed)
subroutine ssht_test_gen_flm_complex (L, spin, flm, seed)
Detailed Description
Definition at line 34 of file ssht_test.f90.
Member Function/Subroutine Documentation
subroutine ssht_test__interface::ssht_test_gen_flm_complex (integer,intent(in) L, integer,intent(in) spin, complex(dpc),dimension(0:l**2-1),intent(out) flm, integer,intent(in) seed)
Definition at line 43 of file ssht_test.f90.
References ssht_error_mod::ssht_error(), ssht_error_mod::SSHT_ERROR_INDEX_INVALID, ssht_error_mod::SSHT_ERROR_MEM_ALLOC_FAIL, ssht_sampling_mod::ssht_sampling_elm2ind(), ssht_sampling_mod::ssht_sampling_ind2elm(), ssht_test_gen_flm_complex(), and ssht_test_gen_flm_real().
subroutine ssht_test__interface::ssht_test_gen_flm_real (integer,intent(in) L, complex(dpc),dimension(0:l**2-1),intent(out) flm, integer,intent(in) seed)
Definition at line 35 of file ssht_test.f90.
The documentation for this interface was generated from the following file:
src/f90/prog/ssht_test.f90