ssht_core_mod Module Reference
ssht_core_mod Module Reference
Functionality to perform spin spherical harmonic transforms on the sphere.
Data Types
interface ssht_core_dh_inverse
Generic interface that points to specific implementation.
interface ssht_core_dh_forward
Generic interface that points to specific implementation.
interface ssht_core_dh_inverse_real
Generic interface that points to specific implementation.
interface ssht_core_dh_forward_real
Generic interface that points to specific implementation.
interface ssht_core_gl_inverse
Generic interface that points to specific implementation.
interface ssht_core_gl_forward
Generic interface that points to specific implementation.
interface ssht_core_gl_inverse_real
Generic interface that points to specific implementation.
interface ssht_core_gl_forward_real
Generic interface that points to specific implementation.
interface ssht_core_mweo_inverse
Generic interface that points to specific implementation.
interface ssht_core_mweo_forward
Generic interface that points to specific implementation.
interface ssht_core_mweo_inverse_real
Generic interface that points to specific implementation.
interface ssht_core_mweo_forward_real
Generic interface that points to specific implementation.
interface ssht_core_mweo_inverse_rsp
Generic interface that points to specific implementation.
interface ssht_core_mweo_forward_rsp
Generic interface that points to specific implementation.
interface ssht_core_mweo_inverse_real_rsp
Generic interface that points to specific implementation.
interface ssht_core_mweo_forward_real_rsp
Generic interface that points to specific implementation.
interface ssht_core_mw_inverse
Generic interface that points to specific implementation.
interface ssht_core_mw_forward
Generic interface that points to specific implementation.
interface ssht_core_mw_inverse_real
Generic interface that points to specific implementation.
interface ssht_core_mw_forward_real
Generic interface that points to specific implementation.
interface ssht_core_mw_inverse_rsp
Generic interface that points to specific implementation.
interface ssht_core_mw_forward_rsp
Generic interface that points to specific implementation.
interface ssht_core_mw_inverse_real_rsp
Generic interface that points to specific implementation.
interface ssht_core_mw_forward_real_rsp
Generic interface that points to specific implementation.
Functions/Subroutines
subroutine ssht_core_mweo_inverse_sp (f, f_sp, phi_sp, flm, L, spin, verbosity)
South pole wrapper for inverse transform using MWEO method.
subroutine ssht_core_mweo_forward_sp (flm, f, f_sp, phi_sp, L, spin, verbosity)
South pole wrapper for forward transform using MWEO method.
subroutine ssht_core_mweo_inverse_real_sp (f, f_sp, flm, L, verbosity)
South pole wrapper for inverse transform of real scalar function using MWEO method.
subroutine ssht_core_mweo_forward_real_sp (flm, f, f_sp, L, verbosity)
South pole wrapper for forward transform of real scalar function using MWEO method.
subroutine ssht_core_mw_inverse_sp (f, f_sp, phi_sp, flm, L, spin, verbosity)
South pole wrapper for inverse transform using MW method.
subroutine ssht_core_mw_forward_sp (flm, f, f_sp, phi_sp, L, spin, verbosity)
South pole wrapper for forward transform using MW method.
subroutine ssht_core_mw_inverse_real_sp (f, f_sp, flm, L, verbosity)
South pole wrapper for inverse transform of real scalar function using MW method.
subroutine ssht_core_mw_forward_real_sp (flm, f, f_sp, L, verbosity)
South pole wrapper for forward transform of real scalar function using MW method.
subroutine ssht_core_dh_inverse_direct (f, flm, L, spin, verbosity)
Compute inverse transform for DH method using direct evaluation with dlmn evaluated for each theta.
subroutine ssht_core_dh_inverse_direct_factored (f, flm, L, spin, verbosity)
Compute inverse transform for DH method using direct evaluation but dlmn factored, i.e. dlmn evaluated at PI/2.
subroutine ssht_core_dh_inverse_sov_direct (f, flm, L, spin, verbosity)
Compute inverse transform for DH method using separation of variables but only discrete (not fast) Fourier transforms.
subroutine ssht_core_dh_inverse_sov (f, flm, L, spin, verbosity)
Compute inverse transform for DH method using separation of variables and fast Fourier transforms.
subroutine ssht_core_dh_inverse_sov_sym (f, flm, L, spin, verbosity)
Compute inverse transform for DH method using separation of variables, fast Fourier transforms and exploiting all symmetries (for complex spin signal).
subroutine ssht_core_dh_inverse_sov_sym_real (f, flm, L, verbosity)
Compute inverse transform for DH method of real scalar signal using separation of variables, fast Fourier transforms and exploiting all symmetries (including additional symmetries for real signals).
subroutine ssht_core_gl_inverse_sov_sym (f, flm, L, spin, verbosity)
Compute inverse transform for GL method using separation of variables, fast Fourier transforms and exploiting all symmetries (for complex spin signal).
subroutine ssht_core_gl_inverse_sov_sym_real (f, flm, L, verbosity)
Compute inverse transform for GL method of real scalar signal using separation of variables, fast Fourier transforms and exploiting all symmetries (including additional symmetries for real signals).
subroutine ssht_core_mweo_inverse_direct (f, flm, L, spin, verbosity)
Compute inverse transform for MWEO method using direct evaluation with dlmn evaluated for each theta.
subroutine ssht_core_mweo_inverse_sov_direct (f, flm, L, spin, verbosity)
Compute inverse transform for MWEO method using separation of variables but only discrete (not fast) Fourier transforms.
subroutine ssht_core_mweo_inverse_sov (f, flm, L, spin, verbosity)
Compute inverse transform for MWEO method using separation of variables and fast Fourier transforms.
subroutine ssht_core_mweo_inverse_sov_sym (f, flm, L, spin, verbosity)
Compute inverse transform for MWEO method using separation of variables, fast Fourier transforms and exploiting all symmetries (for complex spin signal).
subroutine ssht_core_mweo_inverse_sov_sym_real (f, flm, L, verbosity)
Compute inverse transform for MWEO method of real scalar signal using separation of variables, fast Fourier transforms and exploiting all symmetries (including additional symmetries for real signals).
subroutine ssht_core_mw_inverse_sov_direct (f, flm, L, spin, verbosity)
Compute inverse transform for MW method using separation of variables but only discrete (not fast) Fourier transforms.
subroutine ssht_core_mw_inverse_sov (f, flm, L, spin, verbosity)
Compute inverse transform for MW method using separation of variables and fast Fourier transforms.
subroutine ssht_core_mw_inverse_sov_sym (f, flm, L, spin, verbosity)
Compute inverse transform for MW method using separation of variables, fast Fourier transforms and exploiting all symmetries (for complex spin signal).
subroutine ssht_core_mw_inverse_sov_sym_real (f, flm, L, verbosity)
Compute inverse transform for MW method of real scalar signal using separation of variables, fast Fourier transforms and exploiting all symmetries (including additional symmetries for real signals).
subroutine ssht_core_dh_forward_sov_direct (flm, f, L, spin, verbosity)
Compute forward transform for DH method using separation of variables but only discrete (not fast) Fourier transforms.
subroutine ssht_core_dh_forward_sov (flm, f, L, spin, verbosity)
Compute forward transform for DH method using separation of variables and fast Fourier transforms.
subroutine ssht_core_dh_forward_sov_sym (flm, f, L, spin, verbosity)
Compute forward transform for DH method using separation of variables, fast Fourier transforms and exploiting all symmetries (for complex spin signal).
subroutine ssht_core_dh_forward_sov_sym_real (flm, f, L, verbosity)
Compute forward transform for DH method of real scalar signal using separation of variables, fast Fourier transforms and exploiting all symmetries (including additional symmetries for real signals).
subroutine ssht_core_gl_forward_sov_sym (flm, f, L, spin, verbosity)
Compute forward transform for GL method using separation of variables, fast Fourier transforms and exploiting all symmetries (for complex spin signal).
subroutine ssht_core_gl_forward_sov_sym_real (flm, f, L, verbosity)
Compute forward transform for GL method of real scalar signal using separation of variables, fast Fourier transforms and exploiting all symmetries (including additional symmetries for real signals).
subroutine ssht_core_mweo_forward_sov_direct (flm, f, L, spin, verbosity)
Compute forward transform for MWEO method using separation of variables but only discrete (not fast) Fourier transforms.
subroutine ssht_core_mweo_forward_sov (flm, f, L, spin, verbosity)
Compute forward transform for MWEO method using separation of variables and fast Fourier transforms.
subroutine ssht_core_mweo_forward_sov_conv (flm, f, L, spin, verbosity)
Compute forward transform for MWEO method using separation of variables, fast Fourier transforms and performing convolution with weights as product in transformed space.
subroutine ssht_core_mweo_forward_sov_conv_sym (flm, f, L, spin, verbosity)
Compute forward transform for MWEO method using separation of variables, fast Fourier transforms, performing convolution with weights as product in transformed space and exploiting all symmetries (for complex spin signal).
subroutine ssht_core_mweo_forward_sov_conv_sym_real (flm, f, L, verbosity)
Compute forward transform for MWEO method of real scalar signal using separation of variables, fast Fourier transforms, performing convolution with weights as product in transformed space and exploiting all symmetries (including additional symmetries for real signals).
subroutine ssht_core_mw_forward_sov_direct (flm, f, L, spin, verbosity)
Compute forward transform for MW method using separation of variables but only discrete (not fast) Fourier transforms.
subroutine ssht_core_mw_forward_sov (flm, f, L, spin, verbosity)
Compute forward transform for MW method using separation of variables and fast Fourier transforms.
subroutine ssht_core_mw_forward_sov_conv (flm, f, L, spin, verbosity)
Compute forward transform for MW method using separation of variables, fast Fourier transforms and performing convolution with weights as product in transformed space.
subroutine ssht_core_mw_forward_sov_conv_sym (flm, f, L, spin, verbosity)
Compute forward transform for MW method using separation of variables, fast Fourier transforms, performing convolution with weights as product in transformed space and exploiting all symmetries (for complex spin signal).
subroutine ssht_core_mw_forward_sov_conv_sym_real (flm, f, L, verbosity)
Compute forward transform for MW method of real scalar signal using separation of variables, fast Fourier transforms, performing convolution with weights as product in transformed space and exploiting all symmetries (including additional symmetries for real signals).
integer digit (L)
Compute number of digits required to display integer (must be less than 25).
Variables
integer, parameter FFTW_ESTIMATE = 64
integer, parameter FFTW_MEASURE = 0
integer, parameter FFTW_FORWARD = -1
integer, parameter FFTW_BACKWARD = 1
Detailed Description
Functionality to perform spin spherical harmonic transforms on the sphere.
Author:
Jason McEwen
Function/Subroutine Documentation
integer ssht_core_mod::digit (integer,intent(in) L) [private]
Compute number of digits required to display integer (must be less than 25).
Variables:
L: Integer considered [input].
d: Number of digits [output].
Author:
Jason McEwen
Definition at line 5703 of file ssht_core_mod.f90.
Referenced by ssht_core_dh_forward_sov(), ssht_core_dh_forward_sov_direct(), ssht_core_dh_forward_sov_sym(), ssht_core_dh_forward_sov_sym_real(), ssht_core_dh_inverse_direct(), ssht_core_dh_inverse_direct_factored(), ssht_core_dh_inverse_sov(), ssht_core_dh_inverse_sov_direct(), ssht_core_dh_inverse_sov_sym(), ssht_core_dh_inverse_sov_sym_real(), ssht_core_gl_forward_sov_sym(), ssht_core_gl_forward_sov_sym_real(), ssht_core_gl_inverse_sov_sym(), ssht_core_gl_inverse_sov_sym_real(), ssht_core_mw_forward_sov(), ssht_core_mw_forward_sov_conv(), ssht_core_mw_forward_sov_conv_sym(), ssht_core_mw_forward_sov_conv_sym_real(), ssht_core_mw_forward_sov_direct(), ssht_core_mw_inverse_sov(), ssht_core_mw_inverse_sov_direct(), ssht_core_mw_inverse_sov_sym(), ssht_core_mw_inverse_sov_sym_real(), ssht_core_mweo_forward_sov(), ssht_core_mweo_forward_sov_conv(), ssht_core_mweo_forward_sov_conv_sym(), ssht_core_mweo_forward_sov_conv_sym_real(), ssht_core_mweo_forward_sov_direct(), ssht_core_mweo_inverse_direct(), ssht_core_mweo_inverse_sov(), ssht_core_mweo_inverse_sov_direct(), ssht_core_mweo_inverse_sov_sym(), and ssht_core_mweo_inverse_sov_sym_real().
subroutine ssht_core_mod::ssht_core_dh_forward_sov (complex(dpc),dimension(0:l**2-1),intent(out) flm, complex(dpc),dimension(0:2*l-1 ,0:2*l-2),intent(in) f, integer,dimension(l-1),intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
Compute forward transform for DH method using separation of variables and fast Fourier transforms.
Variables:
flm(0:L**2-1): Harmonic coefficients [output].
f(0:2*L-1, 0:2*L-2): Function on sphere [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 2860 of file ssht_core_mod.f90.
References digit(), FFTW_FORWARD, FFTW_MEASURE, ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_beta_operator(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_dh_t2theta(), ssht_sampling_mod::ssht_sampling_elm2ind(), and ssht_sampling_mod::ssht_sampling_weight_dh().
subroutine ssht_core_mod::ssht_core_dh_forward_sov_direct (complex(dpc),dimension(0:l**2-1),intent(out) flm, complex(dpc),dimension(0:2*l-1 ,0:2*l-2),intent(in) f, integer,dimension(l-1),intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
Compute forward transform for DH method using separation of variables but only discrete (not fast) Fourier transforms.
Notes:
Used for code verification purposes (extremely slow!).
Variables:
flm(0:L**2-1): Harmonic coefficients [output].
f(0:2*L-1, 0:2*L-2): Function on sphere [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 2753 of file ssht_core_mod.f90.
References digit(), ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_beta_operator(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_dh_p2phi(), ssht_sampling_mod::ssht_sampling_dh_t2theta(), ssht_sampling_mod::ssht_sampling_elm2ind(), and ssht_sampling_mod::ssht_sampling_weight_dh().
subroutine ssht_core_mod::ssht_core_dh_forward_sov_sym (complex(dpc),dimension(0:l**2-1),intent(out) flm, complex(dpc),dimension(0:2*l-1 ,0:2*l-2),intent(in) f, integer,dimension(l-1),intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
Compute forward transform for DH method using separation of variables, fast Fourier transforms and exploiting all symmetries (for complex spin signal).
Variables:
flm(0:L**2-1): Harmonic coefficients [output].
f(0:2*L-1, 0:2*L-2): Function on sphere [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 2971 of file ssht_core_mod.f90.
References ssht_types_mod::_dp, digit(), FFTW_FORWARD, FFTW_MEASURE, ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_mod::ssht_dl_halfpi_trapani_fill_eighth2righthalf_table(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_dh_t2theta(), ssht_sampling_mod::ssht_sampling_elm2ind(), and ssht_sampling_mod::ssht_sampling_weight_dh().
subroutine ssht_core_mod::ssht_core_dh_forward_sov_sym_real (complex(dpc),dimension(0:l**2-1),intent(out) flm, real(dp),dimension(0:2*l-1 ,0:2*l-2),intent(in) f, integer,intent(in) L, integer,intent(in),optional verbosity) [private]
Compute forward transform for DH method of real scalar signal using separation of variables, fast Fourier transforms and exploiting all symmetries (including additional symmetries for real signals).
Variables:
flm(0:L**2-1): Harmonic coefficients [output].
f(0:2*L-1, 0:2*L-2): Function on sphere [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 3121 of file ssht_core_mod.f90.
References ssht_types_mod::_dp, digit(), FFTW_MEASURE, ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_mod::ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_dh_t2theta(), ssht_sampling_mod::ssht_sampling_elm2ind(), and ssht_sampling_mod::ssht_sampling_weight_dh().
subroutine ssht_core_mod::ssht_core_dh_inverse_direct (complex(dpc),dimension(0:2*l-1, 0:2*l-2),intent(out) f, complex(dpc),dimension(0:l**2-1),intent(in) flm, integer,dimension(l-1),intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
Compute inverse transform for DH method using direct evaluation with dlmn evaluated for each theta.
Notes:
Used for code verification purposes (extremely slow!).
Variables:
f(0:2*L-1, 0:2*L-2): Function on sphere [output].
flm(0:L**2-1): Harmonic coefficients [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 606 of file ssht_core_mod.f90.
References digit(), ssht_types_mod::I, ssht_types_mod::PI, ssht_dl_mod::ssht_dl_beta_operator(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_dh_p2phi(), ssht_sampling_mod::ssht_sampling_dh_t2theta(), and ssht_sampling_mod::ssht_sampling_elm2ind().
subroutine ssht_core_mod::ssht_core_dh_inverse_direct_factored (complex(dpc),dimension(0:2*l-1, 0:2*l-2),intent(out) f, complex(dpc),dimension(0:l**2-1),intent(in) flm, integer,dimension(l-1),intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
Compute inverse transform for DH method using direct evaluation but dlmn factored, i.e. dlmn evaluated at PI/2.
Notes:
Used for code verification purposes (extremely slow!).
Variables:
f(0:2*L-1, 0:2*L-2): Function on sphere [output].
flm(0:L**2-1): Harmonic coefficients [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 689 of file ssht_core_mod.f90.
References digit(), ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_beta_operator(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_dh_p2phi(), ssht_sampling_mod::ssht_sampling_dh_t2theta(), and ssht_sampling_mod::ssht_sampling_elm2ind().
subroutine ssht_core_mod::ssht_core_dh_inverse_sov (complex(dpc),dimension(0:2*l-1, 0:2*l-2),intent(out) f, complex(dpc),dimension(0:l**2-1),intent(in) flm, integer,dimension(l-1),intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
Compute inverse transform for DH method using separation of variables and fast Fourier transforms.
Variables:
f(0:2*L-1, 0:2*L-2): Function on sphere [output].
flm(0:L**2-1): Harmonic coefficients [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 879 of file ssht_core_mod.f90.
References digit(), FFTW_BACKWARD, FFTW_MEASURE, ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_beta_operator(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_dh_t2theta(), and ssht_sampling_mod::ssht_sampling_elm2ind().
subroutine ssht_core_mod::ssht_core_dh_inverse_sov_direct (complex(dpc),dimension(0:2*l-1, 0:2*l-2),intent(out) f, complex(dpc),dimension(0:l**2-1),intent(in) flm, integer,dimension(l-1),intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
Compute inverse transform for DH method using separation of variables but only discrete (not fast) Fourier transforms.
Notes:
Used for code verification purposes (slow!).
Variables:
f(0:2*L-1, 0:2*L-2): Function on sphere [output].
flm(0:L**2-1): Harmonic coefficients [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 775 of file ssht_core_mod.f90.
References digit(), ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_beta_operator(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_dh_p2phi(), ssht_sampling_mod::ssht_sampling_dh_t2theta(), and ssht_sampling_mod::ssht_sampling_elm2ind().
subroutine ssht_core_mod::ssht_core_dh_inverse_sov_sym (complex(dpc),dimension(0:2*l-1, 0:2*l-2),intent(out) f, complex(dpc),dimension(0:l**2-1),intent(in) flm, integer,intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
Compute inverse transform for DH method using separation of variables, fast Fourier transforms and exploiting all symmetries (for complex spin signal).
Variables:
f(0:2*L-1, 0:2*L-2): Function on sphere [output].
flm(0:L**2-1): Harmonic coefficients [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 988 of file ssht_core_mod.f90.
References ssht_types_mod::_dp, digit(), FFTW_BACKWARD, FFTW_MEASURE, ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_mod::ssht_dl_halfpi_trapani_fill_eighth2righthalf_table(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_dh_t2theta(), and ssht_sampling_mod::ssht_sampling_elm2ind().
subroutine ssht_core_mod::ssht_core_dh_inverse_sov_sym_real (real(dp),dimension(0:2*l-1, 0:2*l-2),intent(out) f, complex(dpc),dimension(0:l**2-1),intent(in) flm, integer,intent(in) L, integer,intent(in),optional verbosity) [private]
Compute inverse transform for DH method of real scalar signal using separation of variables, fast Fourier transforms and exploiting all symmetries (including additional symmetries for real signals).
Variables:
f(0:2*L-1, 0:2*L-2): Function on sphere [output].
flm(0:L**2-1): Harmonic coefficients [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 1151 of file ssht_core_mod.f90.
References ssht_types_mod::_dp, digit(), FFTW_MEASURE, ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_mod::ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_dh_t2theta(), and ssht_sampling_mod::ssht_sampling_elm2ind().
subroutine ssht_core_mod::ssht_core_gl_forward_sov_sym (complex(dpc),dimension(0:l**2-1),intent(out) flm, complex(dpc),dimension(0:l-1 ,0:2*l-2),intent(in) f, integer,dimension(l-1),intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
Compute forward transform for GL method using separation of variables, fast Fourier transforms and exploiting all symmetries (for complex spin signal).
Variables:
flm(0:L**2-1): Harmonic coefficients [output].
f(0:L-1, 0:2*L-2): Function on sphere [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 3297 of file ssht_core_mod.f90.
References ssht_types_mod::_dp, digit(), FFTW_FORWARD, FFTW_MEASURE, ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_mod::ssht_dl_halfpi_trapani_fill_eighth2righthalf_table(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_elm2ind(), and ssht_sampling_mod::ssht_sampling_gl_thetas_weights().
subroutine ssht_core_mod::ssht_core_gl_forward_sov_sym_real (complex(dpc),dimension(0:l**2-1),intent(out) flm, real(dp),dimension(0:l-1 ,0:2*l-2),intent(in) f, integer,intent(in) L, integer,intent(in),optional verbosity) [private]
Compute forward transform for GL method of real scalar signal using separation of variables, fast Fourier transforms and exploiting all symmetries (including additional symmetries for real signals).
Variables:
flm(0:L**2-1): Harmonic coefficients [output].
f(0:L-1, 0:2*L-2): Function on sphere [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 3454 of file ssht_core_mod.f90.
References ssht_types_mod::_dp, digit(), FFTW_MEASURE, ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_mod::ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_elm2ind(), and ssht_sampling_mod::ssht_sampling_gl_thetas_weights().
subroutine ssht_core_mod::ssht_core_gl_inverse_sov_sym (complex(dpc),dimension(0:l-1, 0:2*l-2),intent(out) f, complex(dpc),dimension(0:l**2-1),intent(in) flm, integer,intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
Compute inverse transform for GL method using separation of variables, fast Fourier transforms and exploiting all symmetries (for complex spin signal).
Variables:
f(0:L-1, 0:2*L-2): Function on sphere [output].
flm(0:L**2-1): Harmonic coefficients [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 1301 of file ssht_core_mod.f90.
References ssht_types_mod::_dp, digit(), FFTW_BACKWARD, FFTW_MEASURE, ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_mod::ssht_dl_halfpi_trapani_fill_eighth2righthalf_table(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_elm2ind(), and ssht_sampling_mod::ssht_sampling_gl_thetas_weights().
subroutine ssht_core_mod::ssht_core_gl_inverse_sov_sym_real (real(dp),dimension(0:l-1, 0:2*l-2),intent(out) f, complex(dpc),dimension(0:l**2-1),intent(in) flm, integer,intent(in) L, integer,intent(in),optional verbosity) [private]
Compute inverse transform for GL method of real scalar signal using separation of variables, fast Fourier transforms and exploiting all symmetries (including additional symmetries for real signals).
Variables:
f(0:L-1, 0:2*L-2): Function on sphere [output].
flm(0:L**2-1): Harmonic coefficients [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 1469 of file ssht_core_mod.f90.
References ssht_types_mod::_dp, digit(), FFTW_MEASURE, ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_mod::ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_elm2ind(), and ssht_sampling_mod::ssht_sampling_gl_thetas_weights().
subroutine ssht_core_mod::ssht_core_mw_forward_real_sp (complex(dpc),dimension(0:l**2-1),intent(out) flm, real(dp),dimension(0:l-2, 0:2*l-2),intent(in) f, real(dp),intent(in) f_sp, integer,intent(in) L, integer,intent(in),optional verbosity) [private]
South pole wrapper for forward transform of real scalar function using MW method.
Variables:
flm(0:L**2-1): Harmonic coefficients [input].
f(0:L-2, 0:2*L-2): Function on sphere (excluding sample on South pole) [output].
f_sp: Function on sphere South pole sample [output].
L: Harmonic band-limit [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 556 of file ssht_core_mod.f90.
subroutine ssht_core_mod::ssht_core_mw_forward_sov (complex(dpc),dimension(0:l**2-1),intent(out) flm, complex(dpc),dimension(0:l-1 ,0:2*l-2),intent(in) f, integer,dimension(l-1),intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
Compute forward transform for MW method using separation of variables and fast Fourier transforms.
Variables:
flm(0:L**2-1): Harmonic coefficients [output].
f(0:L-1, 0:2*L-2): Function on sphere [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 4919 of file ssht_core_mod.f90.
References digit(), FFTW_FORWARD, FFTW_MEASURE, ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_beta_operator(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_elm2ind(), and ssht_sampling_mod::ssht_sampling_weight_mw().
subroutine ssht_core_mod::ssht_core_mw_forward_sov_conv (complex(dpc),dimension(0:l**2-1),intent(out) flm, complex(dpc),dimension(0:l-1 ,0:2*l-2),intent(in) f, integer,dimension(l-1),intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
Compute forward transform for MW method using separation of variables, fast Fourier transforms and performing convolution with weights as product in transformed space.
Variables:
flm(0:L**2-1): Harmonic coefficients [output].
f(0:L-1, 0:2*L-2): Function on sphere [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 5046 of file ssht_core_mod.f90.
References digit(), FFTW_BACKWARD, FFTW_FORWARD, FFTW_MEASURE, ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_beta_operator(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_elm2ind(), and ssht_sampling_mod::ssht_sampling_weight_mw().
subroutine ssht_core_mod::ssht_core_mw_forward_sov_conv_sym (complex(dpc),dimension(0:l**2-1),intent(out) flm, complex(dpc),dimension(0:l-1 ,0:2*l-2),intent(in) f, integer,dimension(l-1),intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
Compute forward transform for MW method using separation of variables, fast Fourier transforms, performing convolution with weights as product in transformed space and exploiting all symmetries (for complex spin signal).
Variables:
flm(0:L**2-1): Harmonic coefficients [output].
f(0:L-1, 0:2*L-2): Function on sphere [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 5228 of file ssht_core_mod.f90.
References ssht_types_mod::_dp, digit(), FFTW_BACKWARD, FFTW_FORWARD, FFTW_MEASURE, ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_mod::ssht_dl_halfpi_trapani_fill_eighth2righthalf_table(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_elm2ind(), and ssht_sampling_mod::ssht_sampling_weight_mw().
subroutine ssht_core_mod::ssht_core_mw_forward_sov_conv_sym_real (complex(dpc),dimension(0:l**2-1),intent(out) flm, real(dp),dimension(0:l-1 ,0:2*l-2),intent(in) f, integer,intent(in) L, integer,intent(in),optional verbosity) [private]
Compute forward transform for MW method of real scalar signal using separation of variables, fast Fourier transforms, performing convolution with weights as product in transformed space and exploiting all symmetries (including additional symmetries for real signals).
Variables:
flm(0:L**2-1): Harmonic coefficients [output].
f(0:L-1, 0:2*L-2): Function on sphere [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 5448 of file ssht_core_mod.f90.
References ssht_types_mod::_dp, digit(), FFTW_BACKWARD, FFTW_FORWARD, FFTW_MEASURE, ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_mod::ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_elm2ind(), and ssht_sampling_mod::ssht_sampling_weight_mw().
subroutine ssht_core_mod::ssht_core_mw_forward_sov_direct (complex(dpc),dimension(0:l**2-1),intent(out) flm, complex(dpc),dimension(0:l-1 ,0:2*l-2),intent(in) f, integer,dimension(l-1),intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
Compute forward transform for MW method using separation of variables but only discrete (not fast) Fourier transforms.
Notes:
Used for code verification purposes (extremely slow!).
Variables:
flm(0:L**2-1): Harmonic coefficients [output].
f(0:L-1, 0:2*L-2): Function on sphere [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 4794 of file ssht_core_mod.f90.
References digit(), ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_beta_operator(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_elm2ind(), ssht_sampling_mod::ssht_sampling_mw_p2phi(), ssht_sampling_mod::ssht_sampling_mw_t2theta(), and ssht_sampling_mod::ssht_sampling_weight_mw().
subroutine ssht_core_mod::ssht_core_mw_forward_sp (complex(dpc),dimension(0:l**2-1),intent(out) flm, complex(dpc),dimension(0:l-2 ,0:2*l-2),intent(in) f, complex(dpc),intent(in) f_sp, real(dp),intent(in) phi_sp, integer,intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
South pole wrapper for forward transform using MW method.
Variables:
flm(0:L**2-1): Harmonic coefficients [output].
f(0:L-2, 0:2*L-2): Function on sphere (excluding sample on South pole) [input].
f_sp: Function on sphere South pole sample [input].
phi_sp: Phi angle corresponding to quoted sample at South pole [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 473 of file ssht_core_mod.f90.
References ssht_types_mod::I, and ssht_sampling_mod::ssht_sampling_mw_p2phi().
subroutine ssht_core_mod::ssht_core_mw_inverse_real_sp (real(dp),dimension(0:l-2, 0:2*l-2),intent(out) f, real(dp),intent(out) f_sp, complex(dpc),dimension(0:l**2-1),intent(in) flm, integer,intent(in) L, integer,intent(in),optional verbosity) [private]
South pole wrapper for inverse transform of real scalar function using MW method.
Variables:
f(0:L-2, 0:2*L-2): Function on sphere (excluding sample on South pole) [output].
f_sp: Function on sphere South pole sample [output].
flm(0:L**2-1): Harmonic coefficients [input].
L: Harmonic band-limit [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 518 of file ssht_core_mod.f90.
subroutine ssht_core_mod::ssht_core_mw_inverse_sov (complex(dpc),dimension(0:l-1, 0:2*l-2),intent(out) f, complex(dpc),dimension(0:l**2-1),intent(in) flm, integer,dimension(l-1),intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
Compute inverse transform for MW method using separation of variables and fast Fourier transforms.
Variables:
f(0:L-1, 0:2*L-2): Function on sphere [output].
flm(0:L**2-1): Harmonic coefficients [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 2350 of file ssht_core_mod.f90.
References digit(), FFTW_BACKWARD, FFTW_ESTIMATE, ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_beta_operator(), ssht_types_mod::SSHT_PROMPT, and ssht_sampling_mod::ssht_sampling_elm2ind().
subroutine ssht_core_mod::ssht_core_mw_inverse_sov_direct (complex(dpc),dimension(0:l-1, 0:2*l-2),intent(out) f, complex(dpc),dimension(0:l**2-1),intent(in) flm, integer,dimension(l-1),intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
Compute inverse transform for MW method using separation of variables but only discrete (not fast) Fourier transforms.
Notes:
Used for code verification purposes (slow!).
Variables:
f(0:L-1, 0:2*L-2): Function on sphere [output].
flm(0:L**2-1): Harmonic coefficients [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 2251 of file ssht_core_mod.f90.
References digit(), ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_beta_operator(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_elm2ind(), ssht_sampling_mod::ssht_sampling_mw_p2phi(), and ssht_sampling_mod::ssht_sampling_mw_t2theta().
subroutine ssht_core_mod::ssht_core_mw_inverse_sov_sym (complex(dpc),dimension(0:l-1, 0:2*l-2),intent(out) f, complex(dpc),dimension(0:l**2-1),intent(in) flm, integer,dimension(l-1),intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
Compute inverse transform for MW method using separation of variables, fast Fourier transforms and exploiting all symmetries (for complex spin signal).
Variables:
f(0:L-1, 0:2*L-2): Function on sphere [output].
flm(0:L**2-1): Harmonic coefficients [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 2453 of file ssht_core_mod.f90.
References ssht_types_mod::_dp, digit(), FFTW_BACKWARD, FFTW_ESTIMATE, ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_mod::ssht_dl_halfpi_trapani_fill_eighth2righthalf_table(), ssht_types_mod::SSHT_PROMPT, and ssht_sampling_mod::ssht_sampling_elm2ind().
subroutine ssht_core_mod::ssht_core_mw_inverse_sov_sym_real (real(dp),dimension(0:l-1, 0:2*l-2),intent(out) f, complex(dpc),dimension(0:l**2-1),intent(in) flm, integer,intent(in) L, integer,intent(in),optional verbosity) [private]
Compute inverse transform for MW method of real scalar signal using separation of variables, fast Fourier transforms and exploiting all symmetries (including additional symmetries for real signals).
Variables:
f(0:L-1, 0:2*L-2): Function on sphere [output].
flm(0:L**2-1): Harmonic coefficients [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 2593 of file ssht_core_mod.f90.
References ssht_types_mod::_dp, digit(), FFTW_ESTIMATE, ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_mod::ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), ssht_types_mod::SSHT_PROMPT, and ssht_sampling_mod::ssht_sampling_elm2ind().
subroutine ssht_core_mod::ssht_core_mw_inverse_sp (complex(dpc),dimension(0:l-2, 0:2*l-2),intent(out) f, complex(dpc),intent(out) f_sp, real(dp),intent(out) phi_sp, complex(dpc),dimension(0:l**2-1),intent(in) flm, integer,intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
South pole wrapper for inverse transform using MW method.
Variables:
f(0:L-2, 0:2*L-2): Function on sphere (excluding sample on South pole) [output].
f_sp: Function on sphere South pole sample [output].
phi_sp: Phi angle corresponding to quoted sample at South pole [output].
flm(0:L**2-1): Harmonic coefficients [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 430 of file ssht_core_mod.f90.
References ssht_sampling_mod::ssht_sampling_mw_p2phi().
subroutine ssht_core_mod::ssht_core_mweo_forward_real_sp (complex(dpc),dimension(0:l**2-1),intent(out) flm, real(dp),dimension(0:l-2, 0:2*l-2),intent(in) f, real(dp),intent(in) f_sp, integer,intent(in) L, integer,intent(in),optional verbosity) [private]
South pole wrapper for forward transform of real scalar function using MWEO method.
Variables:
flm(0:L**2-1): Harmonic coefficients [input].
f(0:L-2, 0:2*L-2): Function on sphere (excluding sample on South pole) [output].
f_sp: Function on sphere South pole sample [output].
L: Harmonic band-limit [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 385 of file ssht_core_mod.f90.
subroutine ssht_core_mod::ssht_core_mweo_forward_sov (complex(dpc),dimension(0:l**2-1),intent(out) flm, complex(dpc),dimension(0:l-1 ,0:2*l-2),intent(in) f, integer,dimension(l-1),intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
Compute forward transform for MWEO method using separation of variables and fast Fourier transforms.
Variables:
flm(0:L**2-1): Harmonic coefficients [output].
f(0:L-1, 0:2*L-2): Function on sphere [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 3778 of file ssht_core_mod.f90.
References digit(), FFTW_ESTIMATE, FFTW_FORWARD, ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_beta_operator(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_elm2ind(), and ssht_sampling_mod::ssht_sampling_weight_mw().
subroutine ssht_core_mod::ssht_core_mweo_forward_sov_conv (complex(dpc),dimension(0:l**2-1),intent(out) flm, complex(dpc),dimension(0:l-1 ,0:2*l-2),intent(in) f, integer,dimension(l-1),intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
Compute forward transform for MWEO method using separation of variables, fast Fourier transforms and performing convolution with weights as product in transformed space.
Variables:
flm(0:L**2-1): Harmonic coefficients [output].
f(0:L-1, 0:2*L-2): Function on sphere [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 3944 of file ssht_core_mod.f90.
References digit(), FFTW_BACKWARD, FFTW_ESTIMATE, FFTW_FORWARD, FFTW_MEASURE, ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_beta_operator(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_elm2ind(), and ssht_sampling_mod::ssht_sampling_weight_mw().
subroutine ssht_core_mod::ssht_core_mweo_forward_sov_conv_sym (complex(dpc),dimension(0:l**2-1),intent(out) flm, complex(dpc),dimension(0:l-1 ,0:2*l-2),intent(in) f, integer,dimension(l-1),intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
Compute forward transform for MWEO method using separation of variables, fast Fourier transforms, performing convolution with weights as product in transformed space and exploiting all symmetries (for complex spin signal).
Variables:
flm(0:L**2-1): Harmonic coefficients [output].
f(0:L-1, 0:2*L-2): Function on sphere [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 4197 of file ssht_core_mod.f90.
References ssht_types_mod::_dp, digit(), FFTW_BACKWARD, FFTW_ESTIMATE, FFTW_FORWARD, FFTW_MEASURE, ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_mod::ssht_dl_halfpi_trapani_fill_eighth2righthalf_table(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_elm2ind(), and ssht_sampling_mod::ssht_sampling_weight_mw().
subroutine ssht_core_mod::ssht_core_mweo_forward_sov_conv_sym_real (complex(dpc),dimension(0:l**2-1),intent(out) flm, real(dp),dimension(0:l-1 ,0:2*l-2),intent(in) f, integer,intent(in) L, integer,intent(in),optional verbosity) [private]
Compute forward transform for MWEO method of real scalar signal using separation of variables, fast Fourier transforms, performing convolution with weights as product in transformed space and exploiting all symmetries (including additional symmetries for real signals).
Variables:
flm(0:L**2-1): Harmonic coefficients [output].
f(0:L-1, 0:2*L-2): Function on sphere [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 4488 of file ssht_core_mod.f90.
References ssht_types_mod::_dp, digit(), FFTW_BACKWARD, FFTW_ESTIMATE, FFTW_FORWARD, FFTW_MEASURE, ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_mod::ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_elm2ind(), and ssht_sampling_mod::ssht_sampling_weight_mw().
subroutine ssht_core_mod::ssht_core_mweo_forward_sov_direct (complex(dpc),dimension(0:l**2-1),intent(out) flm, complex(dpc),dimension(0:l-1 ,0:2*l-2),intent(in) f, integer,dimension(l-1),intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
Compute forward transform for MWEO method using separation of variables but only discrete (not fast) Fourier transforms.
Notes:
Used for code verification purposes (extremely slow!).
Variables:
flm(0:L**2-1): Harmonic coefficients [output].
f(0:L-1, 0:2*L-2): Function on sphere [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 3637 of file ssht_core_mod.f90.
References digit(), ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_beta_operator(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_elm2ind(), ssht_sampling_mod::ssht_sampling_mweo_p2phi(), ssht_sampling_mod::ssht_sampling_mweo_t2theta(), and ssht_sampling_mod::ssht_sampling_weight_mw().
subroutine ssht_core_mod::ssht_core_mweo_forward_sp (complex(dpc),dimension(0:l**2-1),intent(out) flm, complex(dpc),dimension(0:l-2 ,0:2*l-2),intent(in) f, complex(dpc),intent(in) f_sp, real(dp),intent(in) phi_sp, integer,intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
South pole wrapper for forward transform using MWEO method.
Variables:
flm(0:L**2-1): Harmonic coefficients [output].
f(0:L-2, 0:2*L-2): Function on sphere (excluding sample on South pole) [input].
f_sp: Function on sphere South pole sample [input].
phi_sp: Phi angle corresponding to quoted sample at South pole [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 302 of file ssht_core_mod.f90.
References ssht_types_mod::I, and ssht_sampling_mod::ssht_sampling_mweo_p2phi().
subroutine ssht_core_mod::ssht_core_mweo_inverse_direct (complex(dpc),dimension(0:l-1, 0:2*l-2),intent(out) f, complex(dpc),dimension(0:l**2-1),intent(in) flm, integer,dimension(l-1),intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
Compute inverse transform for MWEO method using direct evaluation with dlmn evaluated for each theta.
Notes:
Used for code verification purposes (extremely slow!).
Variables:
f(0:L-1, 0:2*L-2): Function on sphere [output].
flm(0:L**2-1): Harmonic coefficients [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 1626 of file ssht_core_mod.f90.
References digit(), ssht_types_mod::I, ssht_types_mod::PI, ssht_dl_mod::ssht_dl_beta_operator(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_elm2ind(), ssht_sampling_mod::ssht_sampling_mweo_p2phi(), and ssht_sampling_mod::ssht_sampling_mweo_t2theta().
subroutine ssht_core_mod::ssht_core_mweo_inverse_real_sp (real(dp),dimension(0:l-2, 0:2*l-2),intent(out) f, real(dp),intent(out) f_sp, complex(dpc),dimension(0:l**2-1),intent(in) flm, integer,intent(in) L, integer,intent(in),optional verbosity) [private]
South pole wrapper for inverse transform of real scalar function using MWEO method.
Variables:
f(0:L-2, 0:2*L-2): Function on sphere (excluding sample on South pole) [output].
f_sp: Function on sphere South pole sample [output].
flm(0:L**2-1): Harmonic coefficients [input].
L: Harmonic band-limit [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 347 of file ssht_core_mod.f90.
subroutine ssht_core_mod::ssht_core_mweo_inverse_sov (complex(dpc),dimension(0:l-1, 0:2*l-2),intent(out) f, complex(dpc),dimension(0:l**2-1),intent(in) flm, integer,dimension(l-1),intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
Compute inverse transform for MWEO method using separation of variables and fast Fourier transforms.
Variables:
f(0:L-1, 0:2*L-2): Function on sphere [output].
flm(0:L**2-1): Harmonic coefficients [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 1810 of file ssht_core_mod.f90.
References digit(), FFTW_BACKWARD, FFTW_ESTIMATE, ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_beta_operator(), ssht_types_mod::SSHT_PROMPT, and ssht_sampling_mod::ssht_sampling_elm2ind().
subroutine ssht_core_mod::ssht_core_mweo_inverse_sov_direct (complex(dpc),dimension(0:l-1, 0:2*l-2),intent(out) f, complex(dpc),dimension(0:l**2-1),intent(in) flm, integer,dimension(l-1),intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
Compute inverse transform for MWEO method using separation of variables but only discrete (not fast) Fourier transforms.
Notes:
Used for code verification purposes (slow!).
Variables:
f(0:L-1, 0:2*L-2): Function on sphere [output].
flm(0:L**2-1): Harmonic coefficients [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 1711 of file ssht_core_mod.f90.
References digit(), ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_beta_operator(), ssht_types_mod::SSHT_PROMPT, ssht_sampling_mod::ssht_sampling_elm2ind(), ssht_sampling_mod::ssht_sampling_mweo_p2phi(), and ssht_sampling_mod::ssht_sampling_mweo_t2theta().
subroutine ssht_core_mod::ssht_core_mweo_inverse_sov_sym (complex(dpc),dimension(0:l-1, 0:2*l-2),intent(out) f, complex(dpc),dimension(0:l**2-1),intent(in) flm, integer,dimension(l-1),intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
Compute inverse transform for MWEO method using separation of variables, fast Fourier transforms and exploiting all symmetries (for complex spin signal).
Variables:
f(0:L-1, 0:2*L-2): Function on sphere [output].
flm(0:L**2-1): Harmonic coefficients [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 1934 of file ssht_core_mod.f90.
References ssht_types_mod::_dp, digit(), FFTW_BACKWARD, FFTW_ESTIMATE, ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_mod::ssht_dl_halfpi_trapani_fill_eighth2righthalf_table(), ssht_types_mod::SSHT_PROMPT, and ssht_sampling_mod::ssht_sampling_elm2ind().
subroutine ssht_core_mod::ssht_core_mweo_inverse_sov_sym_real (real(dp),dimension(0:l-1, 0:2*l-2),intent(out) f, complex(dpc),dimension(0:l**2-1),intent(in) flm, integer,intent(in) L, integer,intent(in),optional verbosity) [private]
Compute inverse transform for MWEO method of real scalar signal using separation of variables, fast Fourier transforms and exploiting all symmetries (including additional symmetries for real signals).
Variables:
f(0:L-1, 0:2*L-2): Function on sphere [output].
flm(0:L**2-1): Harmonic coefficients [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 2094 of file ssht_core_mod.f90.
References ssht_types_mod::_dp, digit(), FFTW_ESTIMATE, ssht_types_mod::I, ssht_types_mod::PI, ssht_types_mod::PION2, ssht_dl_mod::ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_mod::ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), ssht_types_mod::SSHT_PROMPT, and ssht_sampling_mod::ssht_sampling_elm2ind().
subroutine ssht_core_mod::ssht_core_mweo_inverse_sp (complex(dpc),dimension(0:l-2, 0:2*l-2),intent(out) f, complex(dpc),intent(out) f_sp, real(dp),intent(out) phi_sp, complex(dpc),dimension(0:l**2-1),intent(in) flm, integer,intent(in) L, integer,intent(in) spin, integer,intent(in),optional verbosity) [private]
South pole wrapper for inverse transform using MWEO method.
Variables:
f(0:L-2, 0:2*L-2): Function on sphere (excluding sample on South pole) [output].
f_sp: Function on sphere South pole sample [output].
phi_sp: Phi angle corresponding to quoted sample at South pole [output].
flm(0:L**2-1): Harmonic coefficients [input].
L: Harmonic band-limit [input].
spin: Spin number [input].
verbosity: Verbosity flag [optional input].
Author:
Jason McEwen
Definition at line 259 of file ssht_core_mod.f90.
References ssht_sampling_mod::ssht_sampling_mweo_p2phi().
Variable Documentation
integer,parameter ssht_core_mod::FFTW_BACKWARD = 1
Definition at line 212 of file ssht_core_mod.f90.
Referenced by ssht_core_dh_inverse_sov(), ssht_core_dh_inverse_sov_sym(), ssht_core_gl_inverse_sov_sym(), ssht_core_mw_forward_sov_conv(), ssht_core_mw_forward_sov_conv_sym(), ssht_core_mw_forward_sov_conv_sym_real(), ssht_core_mw_inverse_sov(), ssht_core_mw_inverse_sov_sym(), ssht_core_mweo_forward_sov_conv(), ssht_core_mweo_forward_sov_conv_sym(), ssht_core_mweo_forward_sov_conv_sym_real(), ssht_core_mweo_inverse_sov(), and ssht_core_mweo_inverse_sov_sym().
integer,parameter ssht_core_mod::FFTW_ESTIMATE = 64
Definition at line 211 of file ssht_core_mod.f90.
Referenced by ssht_core_mw_inverse_sov(), ssht_core_mw_inverse_sov_sym(), ssht_core_mw_inverse_sov_sym_real(), ssht_core_mweo_forward_sov(), ssht_core_mweo_forward_sov_conv(), ssht_core_mweo_forward_sov_conv_sym(), ssht_core_mweo_forward_sov_conv_sym_real(), ssht_core_mweo_inverse_sov(), ssht_core_mweo_inverse_sov_sym(), and ssht_core_mweo_inverse_sov_sym_real().
integer,parameter ssht_core_mod::FFTW_FORWARD = -1
Definition at line 212 of file ssht_core_mod.f90.
Referenced by ssht_core_dh_forward_sov(), ssht_core_dh_forward_sov_sym(), ssht_core_gl_forward_sov_sym(), ssht_core_mw_forward_sov(), ssht_core_mw_forward_sov_conv(), ssht_core_mw_forward_sov_conv_sym(), ssht_core_mw_forward_sov_conv_sym_real(), ssht_core_mweo_forward_sov(), ssht_core_mweo_forward_sov_conv(), ssht_core_mweo_forward_sov_conv_sym(), and ssht_core_mweo_forward_sov_conv_sym_real().
integer,parameter ssht_core_mod::FFTW_MEASURE = 0
Definition at line 211 of file ssht_core_mod.f90.
Referenced by ssht_core_dh_forward_sov(), ssht_core_dh_forward_sov_sym(), ssht_core_dh_forward_sov_sym_real(), ssht_core_dh_inverse_sov(), ssht_core_dh_inverse_sov_sym(), ssht_core_dh_inverse_sov_sym_real(), ssht_core_gl_forward_sov_sym(), ssht_core_gl_forward_sov_sym_real(), ssht_core_gl_inverse_sov_sym(), ssht_core_gl_inverse_sov_sym_real(), ssht_core_mw_forward_sov(), ssht_core_mw_forward_sov_conv(), ssht_core_mw_forward_sov_conv_sym(), ssht_core_mw_forward_sov_conv_sym_real(), ssht_core_mweo_forward_sov_conv(), ssht_core_mweo_forward_sov_conv_sym(), and ssht_core_mweo_forward_sov_conv_sym_real().