ssht_error_mod Module Reference
ssht_error_mod Module Reference
Functionality to handle errors that may occur in the ssht library. Public ssht error codes are defined, with corresponding private error comments and default halt execution status.
Functions/Subroutines
subroutine ssht_error (error_code, procedure, comment_add, comment_out, halt_in)
Displays error message corresponding to error_code and halt program execution if required.
Variables
integer, parameter SSHT_ERROR_NUM = 12
integer, parameter SSHT_ERROR_NONE = 0
integer, parameter SSHT_ERROR_INIT = 1
integer, parameter SSHT_ERROR_NOT_INIT = 2
integer, parameter SSHT_ERROR_INIT_FAIL = 3
integer, parameter SSHT_ERROR_MEM_ALLOC_FAIL = 4
integer, parameter SSHT_ERROR_ARTH = 5
integer, parameter SSHT_ERROR_SIZE_WARNING = 6
integer, parameter SSHT_ERROR_SIZE_INVALID = 7
integer, parameter SSHT_ERROR_SIZE_NOT_DEF = 8
integer, parameter SSHT_ERROR_ARG_INVALID = 9
integer, parameter SSHT_ERROR_ARG_WARNING = 10
integer, parameter SSHT_ERROR_INDEX_INVALID = 11
integer, parameter SSHT_ERROR_FILEIO = 12
character(len=STRING_LEN),
dimension(ssht_error_num+1),
parameter error_comment = (/ , , , , , , , , , , , , /)
Comment associated with each error type.
logical, dimension(ssht_error_num+1),
parameter halt_default = (/ .false., .true., .true., .true., .true., .true., .false., .true., .true., .true., .false., .true., .true. /)
Default program halt status of each error type.
Detailed Description
Functionality to handle errors that may occur in the ssht library. Public ssht error codes are defined, with corresponding private error comments and default halt execution status.
Author:
Jason McEwen
Function/Subroutine Documentation
subroutine ssht_error_mod::ssht_error (integer,intent(in) error_code, character(len=*),intent(in),optional procedure, character(len=*),intent(in),optional comment_add, character(len=*),intent(inout),optional comment_out, logical,intent(in),optional halt_in)
Displays error message corresponding to error_code and halt program execution if required.
Variables:
error_code: Integer error code.
[procedure]: Procedure name where ssht_error called from. Displayed when error message printed to screen.
[comment_add]: If present, additional comment to append to default error comment.
[comment_out]: If present the error comment is copied to comment_out on output.
[halt_in]: If present overrides default halt value.
Author:
Jason McEwen
Definition at line 124 of file ssht_error_mod.f90.
References error_comment, halt_default, and ssht_types_mod::SSHT_PROMPT.
Referenced by ssht_dl_mod::ssht_dl_beta_risbo_full(), ssht_dl_mod::ssht_dl_beta_risbo_full_table(), ssht_dl_mod::ssht_dl_beta_risbo_half_table(), and ssht_test__interface::ssht_test_gen_flm_complex().
Variable Documentation
character(len=STRING_LEN),dimension(ssht_error_num+1),parameter ssht_error_mod::error_comment = (/ , , , , , , , , , , , , /)
Comment associated with each error type.
Definition at line 60 of file ssht_error_mod.f90.
Referenced by ssht_error().
logical,dimension(ssht_error_num+1),parameter ssht_error_mod::halt_default = (/ .false., .true., .true., .true., .true., .true., .false., .true., .true., .true., .false., .true., .true. /)
Default program halt status of each error type.
Definition at line 79 of file ssht_error_mod.f90.
Referenced by ssht_error().
integer,parameter ssht_error_mod::SSHT_ERROR_ARG_INVALID = 9
Definition at line 41 of file ssht_error_mod.f90.
Referenced by ssht_dl_mod::ssht_dl_beta_risbo_full(), ssht_dl_mod::ssht_dl_beta_risbo_full_table(), and ssht_dl_mod::ssht_dl_beta_risbo_half_table().
integer,parameter ssht_error_mod::SSHT_ERROR_ARG_WARNING = 10
Definition at line 41 of file ssht_error_mod.f90.
integer,parameter ssht_error_mod::SSHT_ERROR_ARTH = 5
Definition at line 41 of file ssht_error_mod.f90.
integer,parameter ssht_error_mod::SSHT_ERROR_FILEIO = 12
Definition at line 41 of file ssht_error_mod.f90.
integer,parameter ssht_error_mod::SSHT_ERROR_INDEX_INVALID = 11
Definition at line 41 of file ssht_error_mod.f90.
Referenced by ssht_test__interface::ssht_test_gen_flm_complex().
integer,parameter ssht_error_mod::SSHT_ERROR_INIT = 1
Definition at line 41 of file ssht_error_mod.f90.
integer,parameter ssht_error_mod::SSHT_ERROR_INIT_FAIL = 3
Definition at line 41 of file ssht_error_mod.f90.
integer,parameter ssht_error_mod::SSHT_ERROR_MEM_ALLOC_FAIL = 4
Definition at line 41 of file ssht_error_mod.f90.
Referenced by ssht_test__interface::ssht_test_gen_flm_complex().
integer,parameter ssht_error_mod::SSHT_ERROR_NONE = 0
Definition at line 41 of file ssht_error_mod.f90.
integer,parameter ssht_error_mod::SSHT_ERROR_NOT_INIT = 2
Definition at line 41 of file ssht_error_mod.f90.
integer,parameter ssht_error_mod::SSHT_ERROR_NUM = 12
Definition at line 39 of file ssht_error_mod.f90.
integer,parameter ssht_error_mod::SSHT_ERROR_SIZE_INVALID = 7
Definition at line 41 of file ssht_error_mod.f90.
integer,parameter ssht_error_mod::SSHT_ERROR_SIZE_NOT_DEF = 8
Definition at line 41 of file ssht_error_mod.f90.
integer,parameter ssht_error_mod::SSHT_ERROR_SIZE_WARNING = 6
Definition at line 41 of file ssht_error_mod.f90.