ssht_types_mod Module Reference
ssht_types_mod Module Reference
Definition of intrinsic types and constants used in the ssht library.
Variables
integer, parameter sp = SELECTED_REAL_KIND(5
Type definition for single precision real.
integer, parameter dp = SELECTED_REAL_KIND(12
Type definition for double precision real.
integer, parameter spc = KIND((1.0_sp
Type definition for single precisison complex.
integer, parameter _sp
integer, parameter dpc = KIND((1.0_dp
Type definition for double precision complex.
integer, parameter _dp
real(dp), parameter TOL_RELATIVE_REALITY = 1e-6
Realitive reality tolerance.
integer, parameter STRING_LEN = 256
String buffer length.
real(dp), parameter PI = 3.141592653589793238462643383279502884197_dp
PI definition.
real(dp), parameter PION2 = 1.570796326794896619231321691639751442099_dp
PI/2 definition.
real(dp), parameter SQRT2 = 1.41421356237309504880168872420969807856967_dp
SQRT(2) definition.
complex(dpc), parameter I = (0.0_dp
Complex unit definition.
character(len=*), paramete SSHT_PROMPT)
Verbosity prompt.
Detailed Description
Definition of intrinsic types and constants used in the ssht library.
Author:
Jason McEwen
Variable Documentation
complex(dpc),parameter ssht_types_mod::_dp
Definition at line 58 of file ssht_types_mod.f90.
Referenced by ssht_core_mod::ssht_core_dh_forward_sov_sym(), ssht_core_mod::ssht_core_dh_forward_sov_sym_real(), ssht_core_mod::ssht_core_dh_inverse_sov_sym(), ssht_core_mod::ssht_core_dh_inverse_sov_sym_real(), ssht_core_mod::ssht_core_gl_forward_sov_sym(), ssht_core_mod::ssht_core_gl_forward_sov_sym_real(), ssht_core_mod::ssht_core_gl_inverse_sov_sym(), ssht_core_mod::ssht_core_gl_inverse_sov_sym_real(), ssht_core_mod::ssht_core_mw_forward_sov_conv_sym(), ssht_core_mod::ssht_core_mw_forward_sov_conv_sym_real(), ssht_core_mod::ssht_core_mw_inverse_sov_sym(), ssht_core_mod::ssht_core_mw_inverse_sov_sym_real(), ssht_core_mod::ssht_core_mweo_forward_sov_conv_sym(), ssht_core_mod::ssht_core_mweo_forward_sov_conv_sym_real(), ssht_core_mod::ssht_core_mweo_inverse_sov_sym(), and ssht_core_mod::ssht_core_mweo_inverse_sov_sym_real().
integer,parameter ssht_types_mod::_sp
Definition at line 55 of file ssht_types_mod.f90.
integer,parameter ssht_types_mod::dp = SELECTED_REAL_KIND(12
Type definition for double precision real.
Definition at line 52 of file ssht_types_mod.f90.
integer,parameter ssht_types_mod::dpc = KIND((1.0_dp
Type definition for double precision complex.
Definition at line 58 of file ssht_types_mod.f90.
complex(dpc),parameter ssht_types_mod::I = (0.0_dp
Complex unit definition.
Definition at line 86 of file ssht_types_mod.f90.
Referenced by ssht_core_mod::ssht_core_dh_forward_sov(), ssht_core_mod::ssht_core_dh_forward_sov_direct(), ssht_core_mod::ssht_core_dh_forward_sov_sym(), ssht_core_mod::ssht_core_dh_forward_sov_sym_real(), ssht_core_mod::ssht_core_dh_inverse_direct(), ssht_core_mod::ssht_core_dh_inverse_direct_factored(), ssht_core_mod::ssht_core_dh_inverse_sov(), ssht_core_mod::ssht_core_dh_inverse_sov_direct(), ssht_core_mod::ssht_core_dh_inverse_sov_sym(), ssht_core_mod::ssht_core_dh_inverse_sov_sym_real(), ssht_core_mod::ssht_core_gl_forward_sov_sym(), ssht_core_mod::ssht_core_gl_forward_sov_sym_real(), ssht_core_mod::ssht_core_gl_inverse_sov_sym(), ssht_core_mod::ssht_core_gl_inverse_sov_sym_real(), ssht_core_mod::ssht_core_mw_forward_sov(), ssht_core_mod::ssht_core_mw_forward_sov_conv(), ssht_core_mod::ssht_core_mw_forward_sov_conv_sym(), ssht_core_mod::ssht_core_mw_forward_sov_conv_sym_real(), ssht_core_mod::ssht_core_mw_forward_sov_direct(), ssht_core_mod::ssht_core_mw_forward_sp(), ssht_core_mod::ssht_core_mw_inverse_sov(), ssht_core_mod::ssht_core_mw_inverse_sov_direct(), ssht_core_mod::ssht_core_mw_inverse_sov_sym(), ssht_core_mod::ssht_core_mw_inverse_sov_sym_real(), ssht_core_mod::ssht_core_mweo_forward_sov(), ssht_core_mod::ssht_core_mweo_forward_sov_conv(), ssht_core_mod::ssht_core_mweo_forward_sov_conv_sym(), ssht_core_mod::ssht_core_mweo_forward_sov_conv_sym_real(), ssht_core_mod::ssht_core_mweo_forward_sov_direct(), ssht_core_mod::ssht_core_mweo_forward_sp(), ssht_core_mod::ssht_core_mweo_inverse_direct(), ssht_core_mod::ssht_core_mweo_inverse_sov(), ssht_core_mod::ssht_core_mweo_inverse_sov_direct(), ssht_core_mod::ssht_core_mweo_inverse_sov_sym(), ssht_core_mod::ssht_core_mweo_inverse_sov_sym_real(), and ssht_sampling_mod::ssht_sampling_weight_mw().
real(dp),parameter ssht_types_mod::PI = 3.141592653589793238462643383279502884197_dp
PI definition.
Definition at line 77 of file ssht_types_mod.f90.
Referenced by ssht_core_mod::ssht_core_dh_forward_sov(), ssht_core_mod::ssht_core_dh_forward_sov_direct(), ssht_core_mod::ssht_core_dh_forward_sov_sym(), ssht_core_mod::ssht_core_dh_forward_sov_sym_real(), ssht_core_mod::ssht_core_dh_inverse_direct(), ssht_core_mod::ssht_core_dh_inverse_direct_factored(), ssht_core_mod::ssht_core_dh_inverse_sov(), ssht_core_mod::ssht_core_dh_inverse_sov_direct(), ssht_core_mod::ssht_core_dh_inverse_sov_sym(), ssht_core_mod::ssht_core_dh_inverse_sov_sym_real(), ssht_core_mod::ssht_core_gl_forward_sov_sym(), ssht_core_mod::ssht_core_gl_forward_sov_sym_real(), ssht_core_mod::ssht_core_gl_inverse_sov_sym(), ssht_core_mod::ssht_core_gl_inverse_sov_sym_real(), ssht_core_mod::ssht_core_mw_forward_sov(), ssht_core_mod::ssht_core_mw_forward_sov_conv(), ssht_core_mod::ssht_core_mw_forward_sov_conv_sym(), ssht_core_mod::ssht_core_mw_forward_sov_conv_sym_real(), ssht_core_mod::ssht_core_mw_forward_sov_direct(), ssht_core_mod::ssht_core_mw_inverse_sov(), ssht_core_mod::ssht_core_mw_inverse_sov_direct(), ssht_core_mod::ssht_core_mw_inverse_sov_sym(), ssht_core_mod::ssht_core_mw_inverse_sov_sym_real(), ssht_core_mod::ssht_core_mweo_forward_sov(), ssht_core_mod::ssht_core_mweo_forward_sov_conv(), ssht_core_mod::ssht_core_mweo_forward_sov_conv_sym(), ssht_core_mod::ssht_core_mweo_forward_sov_conv_sym_real(), ssht_core_mod::ssht_core_mweo_forward_sov_direct(), ssht_core_mod::ssht_core_mweo_inverse_direct(), ssht_core_mod::ssht_core_mweo_inverse_sov(), ssht_core_mod::ssht_core_mweo_inverse_sov_direct(), ssht_core_mod::ssht_core_mweo_inverse_sov_sym(), ssht_core_mod::ssht_core_mweo_inverse_sov_sym_real(), ssht_sampling_mod::ssht_sampling_dh_p2phi(), ssht_sampling_mod::ssht_sampling_dh_t2theta(), ssht_sampling_mod::ssht_sampling_gl_p2phi(), ssht_sampling_mod::ssht_sampling_mw_p2phi(), ssht_sampling_mod::ssht_sampling_mw_t2theta(), ssht_sampling_mod::ssht_sampling_mweo_p2phi(), and ssht_sampling_mod::ssht_sampling_mweo_t2theta().
real(dp),parameter ssht_types_mod::PION2 = 1.570796326794896619231321691639751442099_dp
PI/2 definition.
Definition at line 80 of file ssht_types_mod.f90.
Referenced by ssht_core_mod::ssht_core_dh_forward_sov(), ssht_core_mod::ssht_core_dh_forward_sov_direct(), ssht_core_mod::ssht_core_dh_forward_sov_sym(), ssht_core_mod::ssht_core_dh_forward_sov_sym_real(), ssht_core_mod::ssht_core_dh_inverse_direct_factored(), ssht_core_mod::ssht_core_dh_inverse_sov(), ssht_core_mod::ssht_core_dh_inverse_sov_direct(), ssht_core_mod::ssht_core_dh_inverse_sov_sym(), ssht_core_mod::ssht_core_dh_inverse_sov_sym_real(), ssht_core_mod::ssht_core_gl_forward_sov_sym(), ssht_core_mod::ssht_core_gl_forward_sov_sym_real(), ssht_core_mod::ssht_core_gl_inverse_sov_sym(), ssht_core_mod::ssht_core_gl_inverse_sov_sym_real(), ssht_core_mod::ssht_core_mw_forward_sov(), ssht_core_mod::ssht_core_mw_forward_sov_conv(), ssht_core_mod::ssht_core_mw_forward_sov_conv_sym(), ssht_core_mod::ssht_core_mw_forward_sov_conv_sym_real(), ssht_core_mod::ssht_core_mw_forward_sov_direct(), ssht_core_mod::ssht_core_mw_inverse_sov(), ssht_core_mod::ssht_core_mw_inverse_sov_direct(), ssht_core_mod::ssht_core_mw_inverse_sov_sym(), ssht_core_mod::ssht_core_mw_inverse_sov_sym_real(), ssht_core_mod::ssht_core_mweo_forward_sov(), ssht_core_mod::ssht_core_mweo_forward_sov_conv(), ssht_core_mod::ssht_core_mweo_forward_sov_conv_sym(), ssht_core_mod::ssht_core_mweo_forward_sov_conv_sym_real(), ssht_core_mod::ssht_core_mweo_forward_sov_direct(), ssht_core_mod::ssht_core_mweo_inverse_sov(), ssht_core_mod::ssht_core_mweo_inverse_sov_direct(), ssht_core_mod::ssht_core_mweo_inverse_sov_sym(), ssht_core_mod::ssht_core_mweo_inverse_sov_sym_real(), and ssht_sampling_mod::ssht_sampling_weight_mw().
integer,parameter ssht_types_mod::sp = SELECTED_REAL_KIND(5
Type definition for single precision real.
Definition at line 49 of file ssht_types_mod.f90.
integer,parameter ssht_types_mod::spc = KIND((1.0_sp
Type definition for single precisison complex.
Definition at line 55 of file ssht_types_mod.f90.
real(dp),parameter ssht_types_mod::SQRT2 = 1.41421356237309504880168872420969807856967_dp
SQRT(2) definition.
Definition at line 83 of file ssht_types_mod.f90.
Referenced by ssht_dl_mod::ssht_dl_beta_risbo_full(), ssht_dl_mod::ssht_dl_beta_risbo_full_table(), ssht_dl_mod::ssht_dl_beta_risbo_half_table(), and ssht_dl_mod::ssht_dl_halfpi_trapani_eighth_table().
character(len=*),paramete ssht_types_mod::SSHT_PROMPT)
Verbosity prompt.
Definition at line 94 of file ssht_types_mod.f90.
Referenced by ssht_core_mod::ssht_core_dh_forward_sov(), ssht_core_mod::ssht_core_dh_forward_sov_direct(), ssht_core_mod::ssht_core_dh_forward_sov_sym(), ssht_core_mod::ssht_core_dh_forward_sov_sym_real(), ssht_core_mod::ssht_core_dh_inverse_direct(), ssht_core_mod::ssht_core_dh_inverse_direct_factored(), ssht_core_mod::ssht_core_dh_inverse_sov(), ssht_core_mod::ssht_core_dh_inverse_sov_direct(), ssht_core_mod::ssht_core_dh_inverse_sov_sym(), ssht_core_mod::ssht_core_dh_inverse_sov_sym_real(), ssht_core_mod::ssht_core_gl_forward_sov_sym(), ssht_core_mod::ssht_core_gl_forward_sov_sym_real(), ssht_core_mod::ssht_core_gl_inverse_sov_sym(), ssht_core_mod::ssht_core_gl_inverse_sov_sym_real(), ssht_core_mod::ssht_core_mw_forward_sov(), ssht_core_mod::ssht_core_mw_forward_sov_conv(), ssht_core_mod::ssht_core_mw_forward_sov_conv_sym(), ssht_core_mod::ssht_core_mw_forward_sov_conv_sym_real(), ssht_core_mod::ssht_core_mw_forward_sov_direct(), ssht_core_mod::ssht_core_mw_inverse_sov(), ssht_core_mod::ssht_core_mw_inverse_sov_direct(), ssht_core_mod::ssht_core_mw_inverse_sov_sym(), ssht_core_mod::ssht_core_mw_inverse_sov_sym_real(), ssht_core_mod::ssht_core_mweo_forward_sov(), ssht_core_mod::ssht_core_mweo_forward_sov_conv(), ssht_core_mod::ssht_core_mweo_forward_sov_conv_sym(), ssht_core_mod::ssht_core_mweo_forward_sov_conv_sym_real(), ssht_core_mod::ssht_core_mweo_forward_sov_direct(), ssht_core_mod::ssht_core_mweo_inverse_direct(), ssht_core_mod::ssht_core_mweo_inverse_sov(), ssht_core_mod::ssht_core_mweo_inverse_sov_direct(), ssht_core_mod::ssht_core_mweo_inverse_sov_sym(), ssht_core_mod::ssht_core_mweo_inverse_sov_sym_real(), and ssht_error_mod::ssht_error().
integer,parameter ssht_types_mod::STRING_LEN = 256
String buffer length.
Definition at line 74 of file ssht_types_mod.f90.
real(dp),parameter ssht_types_mod::TOL_RELATIVE_REALITY = 1e-6
Realitive reality tolerance.
Definition at line 66 of file ssht_types_mod.f90.