src/f90/prog/ssht_test.f90 File Reference
ssht_test.f90 File Reference
Data Types
interface ssht_test__interface
interface ssht_test_gen_flm_real__interface
interface ssht_test_gen_flm_complex__interface
Functions/Subroutines
program ssht_test
Applies SSHT algorithms to perform inverse and forward spherical harmonic transforms (respectively) to check that the original signal is reconstructed exactly (to numerical precision). Test is performed on a random signal with harmonic coefficients uniformly sampled from (-1,1).
subroutine ssht_test_gen_flm_real (L, flm, seed)
subroutine ssht_test_gen_flm_complex (L, spin, flm, seed)
REAL(dp) ran2_dp (idum)
Function Documentation
REAL(dp) ran2_dp (INTEGER idum)
Definition at line 612 of file ssht_test.f90.
Referenced by ssht_test_gen_flm_complex__interface::ran2_dp(), and ssht_test_gen_flm_real__interface::ran2_dp().
program ssht_test ()
Applies SSHT algorithms to perform inverse and forward spherical harmonic transforms (respectively) to check that the original signal is reconstructed exactly (to numerical precision). Test is performed on a random signal with harmonic coefficients uniformly sampled from (-1,1).
Usage: ssht_test B spin, e.g. ssht_test 64 2
Author:
Jason McEwen
Definition at line 22 of file ssht_test.f90.
subroutine ssht_test_gen_flm_complex (integer,intent(in) L, integer,intent(in) spin, complex(dpc),dimension(0:l**2-1),intent(out) flm, integer,intent(in) seed)
Definition at line 557 of file ssht_test.f90.
Referenced by ssht_test__interface::ssht_test_gen_flm_complex().
subroutine ssht_test_gen_flm_real (integer,intent(in) L, complex(dpc),dimension(0:l**2-1),intent(out) flm, integer,intent(in) seed)
Definition at line 496 of file ssht_test.f90.
Referenced by ssht_test__interface::ssht_test_gen_flm_complex().