src/c/ssht_adjoint.h File Reference
ssht_adjoint.h File Reference
#include <complex.h>
Functions
void ssht_adjoint_mw_inverse_sov_sym (complex double *flm, complex double *f, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_inverse_sov_sym_real (complex double *flm, double *f, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_forward_sov_sym (complex double *f, complex double *flm, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_forward_sov_sym_real (double *f, complex double *flm, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_inverse_sov_sym_pole (complex double *flm, complex double *f, complex double f_sp, double phi_sp, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_inverse_sov_sym_real_pole (complex double *flm, double *f, double f_sp, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_forward_sov_sym_pole (complex double *f, complex double *f_sp, double *phi_sp, complex double *flm, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_forward_sov_sym_real_pole (double *f, double *f_sp, complex double *flm, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_inverse_sov_sym_ss (complex double *flm, complex double *f, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_inverse_sov_sym_ss_real (complex double *flm, double *f, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_forward_sov_sym_ss (complex double *f, complex double *flm, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_forward_sov_sym_ss_real (double *f, complex double *flm, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_inverse_sov_sym_ss_pole (complex double *flm, complex double *f, complex double f_np, double phi_np, complex double f_sp, double phi_sp, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_inverse_sov_sym_ss_real_pole (complex double *flm, double *f, double f_np, double f_sp, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_forward_sov_sym_ss_pole (complex double *f, complex double *f_np, double *phi_np, complex double *f_sp, double *phi_sp, complex double *flm, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_adjoint_mw_forward_sov_sym_ss_real_pole (double *f, double *f_np, double *f_sp, complex double *flm, int L, ssht_dl_method_t dl_method, int verbosity)
Function Documentation
ssht_adjoint_mw_forward_sov_sym()
void ssht_adjoint_mw_forward_sov_sym (complex double * f, complex double * flm, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
Compute adjoint of forward transform for MW method using separation of variables, fast Fourier transforms, performing convolution with weights as product in transformed space and exploiting all symmetries (for complex spin signal).
Parameters
[out] f Function on sphere.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 598 of file ssht_adjoint.c.
References ssht_dl_beta_risbo_eighth_table(), ssht_dl_beta_risbo_fill_eighth2quarter_table(), ssht_dl_calloc(), ssht_dl_get_offset(), ssht_dl_get_stride(), ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), SSHT_DL_QUARTER, SSHT_DL_QUARTER_EXTENDED, SSHT_DL_RISBO, SSHT_DL_TRAPANI, SSHT_ERROR_GENERIC, SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PION2, SSHT_PROMPT, and ssht_sampling_weight_mw().
Referenced by ssht_adjoint_mw_forward_sov_sym_pole().
ssht_adjoint_mw_forward_sov_sym_pole()
void ssht_adjoint_mw_forward_sov_sym_pole (complex double * f, complex double * f_sp, double * phi_sp, complex double * flm, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
South pole wrapper for adjoint forward transform for MW method. The South pole is defined by a single sample and its corresponding phi angle, rather than specifying samples for all phi at the South pole (which are simply related by the rotation of a spin function in its tangent plane).
Parameters
[out] f Function on sphere (excluding South pole).
[out] f_sp Function sample on South pole.
[out] phi_sp Phi angle corresponding to quoted sample at South pole.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 1305 of file ssht_adjoint.c.
References ssht_adjoint_mw_forward_sov_sym(), SSHT_ERROR_MEM_ALLOC_CHECK, and ssht_sampling_mw_p2phi().
ssht_adjoint_mw_forward_sov_sym_real()
void ssht_adjoint_mw_forward_sov_sym_real (double * f, complex double * flm, int L, ssht_dl_method_t dl_method, int verbosity)
Compute adjoint of forward transform for MW method of real scalar signal using separation of variables, fast Fourier transforms, performing convolution with weights as product in transformed space and exploiting all symmetries (including additional symmetries for real signals).
Parameters
[out] f Function on sphere.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 947 of file ssht_adjoint.c.
References ssht_dl_beta_risbo_eighth_table(), ssht_dl_beta_risbo_fill_eighth2quarter_table(), ssht_dl_calloc(), ssht_dl_get_offset(), ssht_dl_get_stride(), ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), SSHT_DL_QUARTER, SSHT_DL_QUARTER_EXTENDED, SSHT_DL_RISBO, SSHT_DL_TRAPANI, SSHT_ERROR_GENERIC, SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PION2, SSHT_PROMPT, and ssht_sampling_weight_mw().
Referenced by ssht_adjoint_mw_forward_sov_sym_real_pole().
ssht_adjoint_mw_forward_sov_sym_real_pole()
void ssht_adjoint_mw_forward_sov_sym_real_pole (double * f, double * f_sp, complex double * flm, int L, ssht_dl_method_t dl_method, int verbosity)
South pole wrapper for adjoint forward transform of real scalar function for MW method. The South pole is defined by a single sample, rather than specifying samples for all phi at the South pole (which for a scalar function are identical).
Parameters
[out] f Function on sphere (excluding South pole).
[out] f_sp Function sample on South pole.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 1351 of file ssht_adjoint.c.
References ssht_adjoint_mw_forward_sov_sym_real(), and SSHT_ERROR_MEM_ALLOC_CHECK.
ssht_adjoint_mw_forward_sov_sym_ss()
void ssht_adjoint_mw_forward_sov_sym_ss (complex double * f, complex double * flm, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
Compute adjoint of forward transform for MW method with symmetric sampling using separation of variables, fast Fourier transforms, performing convolution with weights as product in transformed space and exploiting all symmetries (for complex spin signal).
Parameters
[out] f Function on sphere.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 2037 of file ssht_adjoint.c.
References ssht_dl_beta_risbo_eighth_table(), ssht_dl_beta_risbo_fill_eighth2quarter_table(), ssht_dl_calloc(), ssht_dl_get_offset(), ssht_dl_get_stride(), ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), SSHT_DL_QUARTER, SSHT_DL_QUARTER_EXTENDED, SSHT_DL_RISBO, SSHT_DL_TRAPANI, SSHT_ERROR_GENERIC, SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PION2, SSHT_PROMPT, and ssht_sampling_weight_mw().
Referenced by ssht_adjoint_mw_forward_sov_sym_ss_pole().
ssht_adjoint_mw_forward_sov_sym_ss_pole()
void ssht_adjoint_mw_forward_sov_sym_ss_pole (complex double * f, complex double * f_np, double * phi_np, complex double * f_sp, double * phi_sp, complex double * flm, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
North-South pole wrapper for adjoint forward transform for MW method with symmetric sampling. The poles are defined by single samples and their corresponding phi angle, rather than specifying samples for all phi at the poles (which are simply related by the rotation of a spin function in its tangent plane).
Parameters
[out] f Function on sphere (excluding poles).
[out] f_np Function sample on North pole.
[out] phi_np Phi angle corresponding to quoted sample at North pole.
[out] f_sp Function sample on South pole.
[out] phi_sp Phi angle corresponding to quoted sample at South pole.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 2734 of file ssht_adjoint.c.
References ssht_adjoint_mw_forward_sov_sym_ss(), SSHT_ERROR_MEM_ALLOC_CHECK, and ssht_sampling_mw_ss_p2phi().
ssht_adjoint_mw_forward_sov_sym_ss_real()
void ssht_adjoint_mw_forward_sov_sym_ss_real (double * f, complex double * flm, int L, ssht_dl_method_t dl_method, int verbosity)
Compute adjoint of forward transform for MW method with symmetric sampling of real scalar signal using separation of variables, fast Fourier transforms, performing convolution with weights as product in transformed space and exploiting all symmetries (including additional symmetries for real signals).
Parameters
[out] f Function on sphere.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 2381 of file ssht_adjoint.c.
References ssht_dl_beta_risbo_eighth_table(), ssht_dl_beta_risbo_fill_eighth2quarter_table(), ssht_dl_calloc(), ssht_dl_get_offset(), ssht_dl_get_stride(), ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), SSHT_DL_QUARTER, SSHT_DL_QUARTER_EXTENDED, SSHT_DL_RISBO, SSHT_DL_TRAPANI, SSHT_ERROR_GENERIC, SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PION2, SSHT_PROMPT, and ssht_sampling_weight_mw().
Referenced by ssht_adjoint_mw_forward_sov_sym_ss_real_pole().
ssht_adjoint_mw_forward_sov_sym_ss_real_pole()
void ssht_adjoint_mw_forward_sov_sym_ss_real_pole (double * f, double * f_np, double * f_sp, complex double * flm, int L, ssht_dl_method_t dl_method, int verbosity)
North-South pole wrapper for adjoint forward transform of real scalar function for MW method with symmetric sampling. The poles are defined by single samples, rather than specifying samples for all phi at the poles (which for a scalar function are identical).
Parameters
[out] f Function on sphere (excluding poles).
[out] f_sp Function sample on South pole.
[out] f_np Function sample on North pole.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 2786 of file ssht_adjoint.c.
References ssht_adjoint_mw_forward_sov_sym_ss_real(), and SSHT_ERROR_MEM_ALLOC_CHECK.
ssht_adjoint_mw_inverse_sov_sym()
void ssht_adjoint_mw_inverse_sov_sym (complex double * flm, complex double * f, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
Compute adjoint of inverse transform for MW method using separation of variables, fast Fourier transforms and exploiting all symmetries (for complex spin signal).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 48 of file ssht_adjoint.c.
References ssht_dl_beta_risbo_eighth_table(), ssht_dl_beta_risbo_fill_eighth2quarter_table(), ssht_dl_calloc(), ssht_dl_get_offset(), ssht_dl_get_stride(), ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), SSHT_DL_QUARTER, SSHT_DL_QUARTER_EXTENDED, SSHT_DL_RISBO, SSHT_DL_TRAPANI, SSHT_ERROR_GENERIC, SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PION2, SSHT_PROMPT, and ssht_sampling_elm2ind().
Referenced by ssht_adjoint_mw_inverse_sov_sym_pole().
ssht_adjoint_mw_inverse_sov_sym_pole()
void ssht_adjoint_mw_inverse_sov_sym_pole (complex double * flm, complex double * f, complex double f_sp, double phi_sp, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
South pole wrapper for adjoint inverse transform for MW method. The South pole is defined by a single sample and its corresponding phi angle, rather than specifying samples for all phi at the South pole (which are simply related by the rotation of a spin function in its tangent plane).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere (excluding South pole).
[in] f_sp Function sample on South pole.
[in] phi_sp Phi angle corresponding to quoted sample at South pole.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 1399 of file ssht_adjoint.c.
References ssht_adjoint_mw_inverse_sov_sym(), SSHT_ERROR_MEM_ALLOC_CHECK, and ssht_sampling_mw_p2phi().
ssht_adjoint_mw_inverse_sov_sym_real()
void ssht_adjoint_mw_inverse_sov_sym_real (complex double * flm, double * f, int L, ssht_dl_method_t dl_method, int verbosity)
Compute adjoint of inverse transform for MW method of real scalar signal using separation of variables, fast Fourier transforms and exploiting all symmetries (including additional symmetries for real signals).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere.
[in] L Harmonic band-limit.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 325 of file ssht_adjoint.c.
References ssht_dl_beta_risbo_eighth_table(), ssht_dl_beta_risbo_fill_eighth2quarter_table(), ssht_dl_calloc(), ssht_dl_get_offset(), ssht_dl_get_stride(), ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), SSHT_DL_QUARTER, SSHT_DL_QUARTER_EXTENDED, SSHT_DL_RISBO, SSHT_DL_TRAPANI, SSHT_ERROR_GENERIC, SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PION2, SSHT_PROMPT, and ssht_sampling_elm2ind().
Referenced by ssht_adjoint_mw_inverse_sov_sym_real_pole().
ssht_adjoint_mw_inverse_sov_sym_real_pole()
void ssht_adjoint_mw_inverse_sov_sym_real_pole (complex double * flm, double * f, double f_sp, int L, ssht_dl_method_t dl_method, int verbosity)
South pole wrapper for adjoint inverse transform of real scalar function for MW method. The South pole is defined by a single sample, rather than specifying samples for all phi at the South pole (which for a scalar function are identical).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere (excluding South pole).
[in] f_sp Function sample on South pole.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 1447 of file ssht_adjoint.c.
References ssht_adjoint_mw_inverse_sov_sym_real(), and SSHT_ERROR_MEM_ALLOC_CHECK.
ssht_adjoint_mw_inverse_sov_sym_ss()
void ssht_adjoint_mw_inverse_sov_sym_ss (complex double * flm, complex double * f, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
Compute adjoint of inverse transform for MW method with symmetric sampling using separation of variables, fast Fourier transforms and exploiting all symmetries (for complex spin signal).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 1496 of file ssht_adjoint.c.
References ssht_dl_beta_risbo_eighth_table(), ssht_dl_beta_risbo_fill_eighth2quarter_table(), ssht_dl_calloc(), ssht_dl_get_offset(), ssht_dl_get_stride(), ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), SSHT_DL_QUARTER, SSHT_DL_QUARTER_EXTENDED, SSHT_DL_RISBO, SSHT_DL_TRAPANI, SSHT_ERROR_GENERIC, SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PION2, SSHT_PROMPT, and ssht_sampling_elm2ind().
Referenced by ssht_adjoint_mw_inverse_sov_sym_ss_pole().
ssht_adjoint_mw_inverse_sov_sym_ss_pole()
void ssht_adjoint_mw_inverse_sov_sym_ss_pole (complex double * flm, complex double * f, complex double f_np, double phi_np, complex double f_sp, double phi_sp, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
North-South pole wrapper for adjoint inverse transform for MW method with symmetric sampling. The poles are defined by single samples and their corresponding phi angle, rather than specifying samples for all phi at the poles (which are simply related by the rotation of a spin function in its tangent plane).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere (excluding poles).
[in] f_np Function sample on North pole.
[in] phi_np Phi angle corresponding to quoted sample at North pole.
[in] f_sp Function sample on South pole.
[in] phi_sp Phi angle corresponding to quoted sample at South pole.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 2841 of file ssht_adjoint.c.
References ssht_adjoint_mw_inverse_sov_sym_ss(), SSHT_ERROR_MEM_ALLOC_CHECK, and ssht_sampling_mw_ss_p2phi().
ssht_adjoint_mw_inverse_sov_sym_ss_real()
void ssht_adjoint_mw_inverse_sov_sym_ss_real (complex double * flm, double * f, int L, ssht_dl_method_t dl_method, int verbosity)
Compute adjoint of inverse transform for MW method with symmetric sampling of real scalar signal using separation of variables, fast Fourier transforms and exploiting all symmetries (including additional symmetries for real signals).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere.
[in] L Harmonic band-limit.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 1774 of file ssht_adjoint.c.
References ssht_dl_beta_risbo_eighth_table(), ssht_dl_beta_risbo_fill_eighth2quarter_table(), ssht_dl_calloc(), ssht_dl_get_offset(), ssht_dl_get_stride(), ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), SSHT_DL_QUARTER, SSHT_DL_QUARTER_EXTENDED, SSHT_DL_RISBO, SSHT_DL_TRAPANI, SSHT_ERROR_GENERIC, SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PION2, SSHT_PROMPT, and ssht_sampling_elm2ind().
Referenced by ssht_adjoint_mw_inverse_sov_sym_ss_real_pole().
ssht_adjoint_mw_inverse_sov_sym_ss_real_pole()
void ssht_adjoint_mw_inverse_sov_sym_ss_real_pole (complex double * flm, double * f, double f_np, double f_sp, int L, ssht_dl_method_t dl_method, int verbosity)
North-South pole wrapper for adjoint inverse transform of real scalar function for MW method with symmetric sampling. The poles are defined by single samples, rather than specifying samples for all phi at the poles (which for a scalar function are identical).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere (excluding poles).
[in] f_np Function sample on North pole.
[in] f_sp Function sample on South pole.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosiity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 2894 of file ssht_adjoint.c.
References ssht_adjoint_mw_inverse_sov_sym_ss_real(), and SSHT_ERROR_MEM_ALLOC_CHECK.