src/c/ssht_core.c File Reference
ssht_core.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <complex.h>
#include <fftw3.h>
#include "ssht_types.h"
#include "ssht_error.h"
#include "ssht_dl.h"
#include "ssht_sampling.h"
#include "ssht_core.h"
Macros
#define MAX(a, b) ((a) > (b) ? (a) : (b))
Functions
void ssht_core_mw_inverse_sov_sym (complex double *f, const complex double *flm, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_core_mw_lb_inverse_sov_sym (complex double *f, const complex double *flm, int L0, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_core_mw_inverse_sov_sym_real (double *f, const complex double *flm, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_core_mw_lb_inverse_sov_sym_real (double *f, const complex double *flm, int L0, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_core_mwdirect_inverse (complex double *f, const complex double *flm, int L, int spin, int verbosity)
void ssht_core_mwdirect_inverse_sov (complex double *f, const complex double *flm, int L, int spin, int verbosity)
void ssht_core_mw_forward_sov_conv_sym (complex double *flm, const complex double *f, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_core_mw_lb_forward_sov_conv_sym (complex double *flm, const complex double *f, int L0, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_core_mw_forward_sov_conv_sym_real (complex double *flm, const double *f, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_core_mw_lb_forward_sov_conv_sym_real (complex double *flm, const double *f, int L0, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_core_mw_inverse_sov_sym_pole (complex double *f, complex double *f_sp, double *phi_sp, const complex double *flm, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_core_mw_inverse_sov_sym_real_pole (double *f, double *f_sp, const complex double *flm, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_core_mw_forward_sov_conv_sym_pole (complex double *flm, const complex double *f, complex double f_sp, double phi_sp, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_core_mw_forward_sov_conv_sym_real_pole (complex double *flm, const double *f, double f_sp, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_core_mw_inverse_sov_sym_ss (complex double *f, const complex double *flm, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_core_mw_lb_inverse_sov_sym_ss (complex double *f, const complex double *flm, int L0, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_core_mw_inverse_sov_sym_ss_real (double *f, const complex double *flm, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_core_mw_lb_inverse_sov_sym_ss_real (double *f, const complex double *flm, int L0, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_core_mwdirect_inverse_ss (complex double *f, const complex double *flm, int L, int spin, int verbosity)
void ssht_core_mw_forward_sov_conv_sym_ss (complex double *flm, const complex double *f, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_core_mw_lb_forward_sov_conv_sym_ss (complex double *flm, const complex double *f, int L0, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_core_mw_forward_sov_conv_sym_ss_real (complex double *flm, const double *f, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_core_mw_lb_forward_sov_conv_sym_ss_real (complex double *flm, const double *f, int L0, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_core_mw_inverse_sov_sym_ss_pole (complex double *f, complex double *f_np, double *phi_np, complex double *f_sp, double *phi_sp, const complex double *flm, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_core_mw_inverse_sov_sym_ss_real_pole (double *f, double *f_np, double *f_sp, const complex double *flm, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_core_mw_forward_sov_conv_sym_ss_pole (complex double *flm, const complex double *f, complex double f_np, double phi_np, complex double f_sp, double phi_sp, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
void ssht_core_mw_forward_sov_conv_sym_ss_real_pole (complex double *flm, const double *f, double f_np, double f_sp, int L, ssht_dl_method_t dl_method, int verbosity)
void ssht_core_gl_inverse_sov (complex double *f, const complex double *flm, int L, int spin, int verbosity)
void ssht_core_gl_inverse_sov_real (double *f, const complex double *flm, int L, int verbosity)
void ssht_core_gl_forward_sov (complex double *flm, const complex double *f, int L, int spin, int verbosity)
void ssht_core_gl_forward_sov_real (complex double *flm, const double *f, int L, int verbosity)
void ssht_core_dh_inverse_sov (complex double *f, const complex double *flm, int L, int spin, int verbosity)
void ssht_core_dh_inverse_sov_real (double *f, const complex double *flm, int L, int verbosity)
void ssht_core_dh_forward_sov (complex double *flm, const complex double *f, int L, int spin, int verbosity)
void ssht_core_dh_forward_sov_real (complex double *flm, const double *f, int L, int verbosity)
Detailed Description
Core algorithms to perform spin spherical harmonic transform on the sphere.
Author
Jason McEwen
Definition in file ssht_core.c.
Macro Definition Documentation
MAX
#define MAX (a, b) ((a) > (b) ? (a) : (b))
Definition at line 26 of file ssht_core.c.
Referenced by ssht_core_mw_lb_forward_sov_conv_sym(), ssht_core_mw_lb_forward_sov_conv_sym_real(), ssht_core_mw_lb_forward_sov_conv_sym_ss(), ssht_core_mw_lb_forward_sov_conv_sym_ss_real(), ssht_core_mw_lb_inverse_sov_sym(), ssht_core_mw_lb_inverse_sov_sym_real(), ssht_core_mw_lb_inverse_sov_sym_ss(), and ssht_core_mw_lb_inverse_sov_sym_ss_real().
Function Documentation
ssht_core_dh_forward_sov()
void ssht_core_dh_forward_sov (complex double * flm, const complex double * f, int L, int spin, int verbosity)
Compute forward transform using Driscoll and Healy quadrature with separation of variables.
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 4237 of file ssht_core.c.
References ssht_dl_beta_kostelec_line_table(), SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PROMPT, ssht_sampling_dh_t2theta(), ssht_sampling_elm2ind(), and ssht_sampling_weight_dh().
Referenced by main().
ssht_core_dh_forward_sov_real()
void ssht_core_dh_forward_sov_real (complex double * flm, const double * f, int L, int verbosity)
Compute forward transform of real scalar signal using Driscoll and Healy quadrature with separation of variables (symmetries for real signals are exploited).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 4374 of file ssht_core.c.
References ssht_dl_beta_kostelec_halfline_table(), SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PROMPT, ssht_sampling_dh_t2theta(), ssht_sampling_elm2ind(), and ssht_sampling_weight_dh().
Referenced by main().
ssht_core_dh_inverse_sov()
void ssht_core_dh_inverse_sov (complex double * f, const complex double * flm, int L, int spin, int verbosity)
Compute inverse transform using direct method with separation of variables for DH sampling.
Parameters
[out] f Function on sphere.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 3997 of file ssht_core.c.
References ssht_dl_beta_kostelec_line_table(), SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PROMPT, ssht_sampling_dh_t2theta(), and ssht_sampling_elm2ind().
Referenced by main().
ssht_core_dh_inverse_sov_real()
void ssht_core_dh_inverse_sov_real (double * f, const complex double * flm, int L, int verbosity)
Compute inverse transform of real scalar signal using direct method with separation of variables for DH sampling (symmetries for real signals are exploited).
Parameters
[out] f Function on sphere.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 4116 of file ssht_core.c.
References ssht_dl_beta_kostelec_halfline_table(), SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PROMPT, ssht_sampling_dh_t2theta(), and ssht_sampling_elm2ind().
Referenced by main().
ssht_core_gl_forward_sov()
void ssht_core_gl_forward_sov (complex double * flm, const complex double * f, int L, int spin, int verbosity)
Compute forward transform using Gauss-Legendgre quadrature with separation of variables.
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 3686 of file ssht_core.c.
References ssht_dl_beta_kostelec_line_table(), SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PROMPT, ssht_sampling_elm2ind(), and ssht_sampling_gl_thetas_weights().
Referenced by main().
ssht_core_gl_forward_sov_real()
void ssht_core_gl_forward_sov_real (complex double * flm, const double * f, int L, int verbosity)
Compute forward transform of real scalar signal using Gauss-Legendgre quadrature with separation of variables (symmetries for real signals are exploited).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 3833 of file ssht_core.c.
References ssht_dl_beta_kostelec_halfline_table(), SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PROMPT, ssht_sampling_elm2ind(), and ssht_sampling_gl_thetas_weights().
Referenced by main().
ssht_core_gl_inverse_sov()
void ssht_core_gl_inverse_sov (complex double * f, const complex double * flm, int L, int spin, int verbosity)
Compute inverse transform using direct method with separation of variables for GL sampling.
Parameters
[out] f Function on sphere.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 3422 of file ssht_core.c.
References ssht_dl_beta_kostelec_line_table(), SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PROMPT, ssht_sampling_elm2ind(), and ssht_sampling_gl_thetas_weights().
Referenced by main().
ssht_core_gl_inverse_sov_real()
void ssht_core_gl_inverse_sov_real (double * f, const complex double * flm, int L, int verbosity)
Compute inverse transform of real scalar signal using direct method with separation of variables for GL sampling (symmetries for real signals are exploited).
Parameters
[out] f Function on sphere.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 3553 of file ssht_core.c.
References ssht_dl_beta_kostelec_halfline_table(), SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PROMPT, ssht_sampling_elm2ind(), and ssht_sampling_gl_thetas_weights().
Referenced by main().
ssht_core_mw_forward_sov_conv_sym()
void ssht_core_mw_forward_sov_conv_sym (complex double * flm, const complex double * f, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
Compute forward transform for MW method using separation of variables, fast Fourier transforms, performing convolution with weights as product in transformed space and exploiting all symmetries (for complex spin signal).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 807 of file ssht_core.c.
References ssht_core_mw_lb_forward_sov_conv_sym().
Referenced by main(), and ssht_core_mw_forward_sov_conv_sym_pole().
ssht_core_mw_forward_sov_conv_sym_pole()
void ssht_core_mw_forward_sov_conv_sym_pole (complex double * flm, const complex double * f, complex double f_sp, double phi_sp, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
South pole wrapper for forward transform for MW method. The South pole is defined by a single sample and its corresponding phi angle, rather than specifying samples for all phi at the South pole (which are simply related by the rotation of a spin function in its tangent plane).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere (excluding South pole).
[in] f_sp Function sample on South pole.
[in] phi_sp Phi angle corresponding to quoted sample at South pole.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 1700 of file ssht_core.c.
References ssht_core_mw_forward_sov_conv_sym(), SSHT_ERROR_MEM_ALLOC_CHECK, and ssht_sampling_mw_p2phi().
Referenced by main().
ssht_core_mw_forward_sov_conv_sym_real()
void ssht_core_mw_forward_sov_conv_sym_real (complex double * flm, const double * f, int L, ssht_dl_method_t dl_method, int verbosity)
Compute forward transform for MW method of real scalar signal using separation of variables, fast Fourier transforms, performing convolution with weights as product in transformed space and exploiting all symmetries (including additional symmetries for real signals).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere.
[in] L Harmonic band-limit.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 1200 of file ssht_core.c.
References ssht_core_mw_lb_forward_sov_conv_sym_real().
Referenced by main(), and ssht_core_mw_forward_sov_conv_sym_real_pole().
ssht_core_mw_forward_sov_conv_sym_real_pole()
void ssht_core_mw_forward_sov_conv_sym_real_pole (complex double * flm, const double * f, double f_sp, int L, ssht_dl_method_t dl_method, int verbosity)
South pole wrapper for forward transform of real scalar function for MW method. The South pole is defined by a single sample, rather than specifying samples for all phi at the South pole (which for a scalar function are identical).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere (excluding South pole).
[in] f_sp Function sample on South pole.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 1748 of file ssht_core.c.
References ssht_core_mw_forward_sov_conv_sym_real(), and SSHT_ERROR_MEM_ALLOC_CHECK.
Referenced by main().
ssht_core_mw_forward_sov_conv_sym_ss()
void ssht_core_mw_forward_sov_conv_sym_ss (complex double * flm, const complex double * f, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
Compute forward transform for MW method with symmetric sampling using separation of variables, fast Fourier transforms, performing convolution with weights as product in transformed space and exploiting all symmetries (for complex spin signal).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 2424 of file ssht_core.c.
References ssht_core_mw_lb_forward_sov_conv_sym_ss().
Referenced by main(), and ssht_core_mw_forward_sov_conv_sym_ss_pole().
ssht_core_mw_forward_sov_conv_sym_ss_pole()
void ssht_core_mw_forward_sov_conv_sym_ss_pole (complex double * flm, const complex double * f, complex double f_np, double phi_np, complex double f_sp, double phi_sp, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
North-South pole wrapper for forward transform for MW method with symmetric sampling. The poles are defined by single samples and their corresponding phi angle, rather than specifying samples for all phi at the poles (which are simply related by the rotation of a spin function in its tangent plane).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere (excluding poles).
[in] f_np Function sample on North pole.
[in] phi_np Phi angle corresponding to quoted sample at North pole.
[in] f_sp Function sample on South pole.
[in] phi_sp Phi angle corresponding to quoted sample at South pole.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 3317 of file ssht_core.c.
References ssht_core_mw_forward_sov_conv_sym_ss(), SSHT_ERROR_MEM_ALLOC_CHECK, and ssht_sampling_mw_ss_p2phi().
Referenced by main().
ssht_core_mw_forward_sov_conv_sym_ss_real()
void ssht_core_mw_forward_sov_conv_sym_ss_real (complex double * flm, const double * f, int L, ssht_dl_method_t dl_method, int verbosity)
Compute forward transform for MW method using symmetric sampling of real scalar signal using separation of variables, fast Fourier transforms, performing convolution with weights as product in transformed space and exploiting all symmetries (including additional symmetries for real signals).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere.
[in] L Harmonic band-limit.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 2819 of file ssht_core.c.
References ssht_core_mw_lb_forward_sov_conv_sym_ss_real().
Referenced by main(), and ssht_core_mw_forward_sov_conv_sym_ss_real_pole().
ssht_core_mw_forward_sov_conv_sym_ss_real_pole()
void ssht_core_mw_forward_sov_conv_sym_ss_real_pole (complex double * flm, const double * f, double f_np, double f_sp, int L, ssht_dl_method_t dl_method, int verbosity)
North-South pole wrapper for forward transform of real scalar function for MW method with symmetric sampling. The poles are defined by single samples, rather than specifying samples for all phi at the poles (which for a scalar function are identical).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere (excluding poles).
[in] f_np Function sample on North pole.
[in] f_sp Function sample on South pole.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 3370 of file ssht_core.c.
References ssht_core_mw_forward_sov_conv_sym_ss_real(), and SSHT_ERROR_MEM_ALLOC_CHECK.
Referenced by main().
ssht_core_mw_inverse_sov_sym()
void ssht_core_mw_inverse_sov_sym (complex double * f, const complex double * flm, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
Compute inverse transform for MW method using separation of variables, fast Fourier transforms and exploiting all symmetries (for complex spin signal).
Parameters
[out] f Function on sphere.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 49 of file ssht_core.c.
References ssht_core_mw_lb_inverse_sov_sym().
Referenced by main(), and ssht_core_mw_inverse_sov_sym_pole().
ssht_core_mw_inverse_sov_sym_pole()
void ssht_core_mw_inverse_sov_sym_pole (complex double * f, complex double * f_sp, double * phi_sp, const complex double * flm, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
South pole wrapper for inverse transform for MW method. The South pole is defined by a single sample and its corresponding phi angle, rather than specifying samples for all phi at the South pole (which are simply related by the rotation of a spin function in its tangent plane).
Parameters
[out] f Function on sphere (excluding South pole).
[out] f_sp Function sample on South pole.
[out] phi_sp Phi angle corresponding to quoted sample at South pole.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 1606 of file ssht_core.c.
References ssht_core_mw_inverse_sov_sym(), SSHT_ERROR_MEM_ALLOC_CHECK, and ssht_sampling_mw_p2phi().
Referenced by main().
ssht_core_mw_inverse_sov_sym_real()
void ssht_core_mw_inverse_sov_sym_real (double * f, const complex double * flm, int L, ssht_dl_method_t dl_method, int verbosity)
Compute inverse transform for MW method of real scalar signal using separation of variables, fast Fourier transforms and exploiting all symmetries (including additional symmetries for real signals).
Parameters
[out] f Function on sphere.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 320 of file ssht_core.c.
References ssht_core_mw_lb_inverse_sov_sym_real().
Referenced by main(), and ssht_core_mw_inverse_sov_sym_real_pole().
ssht_core_mw_inverse_sov_sym_real_pole()
void ssht_core_mw_inverse_sov_sym_real_pole (double * f, double * f_sp, const complex double * flm, int L, ssht_dl_method_t dl_method, int verbosity)
South pole wrapper for inverse transform of real scalar function for MW method. The South pole is defined by a single sample, rather than specifying samples for all phi at the South pole (which for a scalar function are identical).
Parameters
[out] f Function on sphere (excluding South pole).
[out] f_sp Function sample on South pole.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 1652 of file ssht_core.c.
References ssht_core_mw_inverse_sov_sym_real(), and SSHT_ERROR_MEM_ALLOC_CHECK.
Referenced by main().
ssht_core_mw_inverse_sov_sym_ss()
void ssht_core_mw_inverse_sov_sym_ss (complex double * f, const complex double * flm, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
Compute inverse transform for MW method with symmetric sampling using separation of variables, fast Fourier transforms and exploiting all symmetries (for complex spin signal).
Parameters
[out] f Function on sphere.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 1796 of file ssht_core.c.
References ssht_core_mw_lb_inverse_sov_sym_ss().
Referenced by main(), and ssht_core_mw_inverse_sov_sym_ss_pole().
ssht_core_mw_inverse_sov_sym_ss_pole()
void ssht_core_mw_inverse_sov_sym_ss_pole (complex double * f, complex double * f_np, double * phi_np, complex double * f_sp, double * phi_sp, const complex double * flm, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
North-South pole wrapper for inverse transform for MW method with symmetric sampling. The poles are defined by single samples and their corresponding phi angle, rather than specifying samples for all phi at the poles (which are simply related by the rotation of a spin function in its tangent plane).
Parameters
[out] f Function on sphere (excluding poles).
[out] f_np Function sample on North pole.
[out] phi_np Phi angle corresponding to quoted sample at North pole.
[out] f_sp Function sample on South pole.
[out] phi_sp Phi angle corresponding to quoted sample at South pole.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 3210 of file ssht_core.c.
References ssht_core_mw_inverse_sov_sym_ss(), SSHT_ERROR_MEM_ALLOC_CHECK, and ssht_sampling_mw_ss_p2phi().
Referenced by main().
ssht_core_mw_inverse_sov_sym_ss_real()
void ssht_core_mw_inverse_sov_sym_ss_real (double * f, const complex double * flm, int L, ssht_dl_method_t dl_method, int verbosity)
Compute inverse transform for MW method with symmetric sampling of real scalar signal using separation of variables, fast Fourier transforms and exploiting all symmetries (including additional symmetries for real signals).
Parameters
[out] f Function on sphere.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 2066 of file ssht_core.c.
References ssht_core_mw_lb_inverse_sov_sym_ss_real().
Referenced by main(), and ssht_core_mw_inverse_sov_sym_ss_real_pole().
ssht_core_mw_inverse_sov_sym_ss_real_pole()
void ssht_core_mw_inverse_sov_sym_ss_real_pole (double * f, double * f_np, double * f_sp, const complex double * flm, int L, ssht_dl_method_t dl_method, int verbosity)
North-South pole wrapper for inverse transform of real scalar function for MW method with symmetric sampling. The poles are defined by single samples, rather than specifying samples for all phi at the poles (which for a scalar function are identical).
Parameters
[out] f Function on sphere (excluding poles).
[out] f_sp Function sample on South pole.
[out] f_np Function sample on North pole.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 3262 of file ssht_core.c.
References ssht_core_mw_inverse_sov_sym_ss_real(), and SSHT_ERROR_MEM_ALLOC_CHECK.
Referenced by main().
ssht_core_mw_lb_forward_sov_conv_sym()
void ssht_core_mw_lb_forward_sov_conv_sym (complex double * flm, const complex double * f, int L0, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
Compute forward transform for MW method using separation of variables, fast Fourier transforms, performing convolution with weights as product in transformed space and exploiting all symmetries (for complex spin signal).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere.
[in] L0 Lower harmonic band-limit.
[in] L Upper harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 834 of file ssht_core.c.
References MAX, ssht_dl_beta_risbo_eighth_table(), ssht_dl_beta_risbo_fill_eighth2quarter_table(), ssht_dl_calloc(), ssht_dl_get_offset(), ssht_dl_get_stride(), ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), SSHT_DL_QUARTER, SSHT_DL_QUARTER_EXTENDED, SSHT_DL_RISBO, SSHT_DL_TRAPANI, SSHT_ERROR_GENERIC, SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PION2, SSHT_PROMPT, ssht_sampling_elm2ind(), and ssht_sampling_weight_mw().
Referenced by main(), and ssht_core_mw_forward_sov_conv_sym().
ssht_core_mw_lb_forward_sov_conv_sym_real()
void ssht_core_mw_lb_forward_sov_conv_sym_real (complex double * flm, const double * f, int L0, int L, ssht_dl_method_t dl_method, int verbosity)
Compute forward transform for MW method of real scalar signal using separation of variables, fast Fourier transforms, performing convolution with weights as product in transformed space and exploiting all symmetries (including additional symmetries for real signals).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere.
[in] L0 Lower harmonic band-limit.
[in] L Upper harmonic band-limit.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 1227 of file ssht_core.c.
References MAX, ssht_dl_beta_risbo_eighth_table(), ssht_dl_beta_risbo_fill_eighth2quarter_table(), ssht_dl_calloc(), ssht_dl_get_offset(), ssht_dl_get_stride(), ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), SSHT_DL_QUARTER, SSHT_DL_QUARTER_EXTENDED, SSHT_DL_RISBO, SSHT_DL_TRAPANI, SSHT_ERROR_GENERIC, SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PION2, SSHT_PROMPT, ssht_sampling_elm2ind(), and ssht_sampling_weight_mw().
Referenced by main(), and ssht_core_mw_forward_sov_conv_sym_real().
ssht_core_mw_lb_forward_sov_conv_sym_ss()
void ssht_core_mw_lb_forward_sov_conv_sym_ss (complex double * flm, const complex double * f, int L0, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
Compute forward transform for MW method with symmetric sampling using separation of variables, fast Fourier transforms, performing convolution with weights as product in transformed space and exploiting all symmetries (for complex spin signal).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere.
[in] L0 Lower harmonic band-limit.
[in] L Upper harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 2451 of file ssht_core.c.
References MAX, ssht_dl_beta_risbo_eighth_table(), ssht_dl_beta_risbo_fill_eighth2quarter_table(), ssht_dl_calloc(), ssht_dl_get_offset(), ssht_dl_get_stride(), ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), SSHT_DL_QUARTER, SSHT_DL_QUARTER_EXTENDED, SSHT_DL_RISBO, SSHT_DL_TRAPANI, SSHT_ERROR_GENERIC, SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PION2, SSHT_PROMPT, ssht_sampling_elm2ind(), and ssht_sampling_weight_mw().
Referenced by main(), and ssht_core_mw_forward_sov_conv_sym_ss().
ssht_core_mw_lb_forward_sov_conv_sym_ss_real()
void ssht_core_mw_lb_forward_sov_conv_sym_ss_real (complex double * flm, const double * f, int L0, int L, ssht_dl_method_t dl_method, int verbosity)
Compute forward transform for MW method using symmetric sampling of real scalar signal using separation of variables, fast Fourier transforms, performing convolution with weights as product in transformed space and exploiting all symmetries (including additional symmetries for real signals).
Parameters
[out] flm Harmonic coefficients.
[in] f Function on sphere.
[in] L0 Lower harmonic band-limit.
[in] L Upper harmonic band-limit.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 2846 of file ssht_core.c.
References MAX, ssht_dl_beta_risbo_eighth_table(), ssht_dl_beta_risbo_fill_eighth2quarter_table(), ssht_dl_calloc(), ssht_dl_get_offset(), ssht_dl_get_stride(), ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), SSHT_DL_QUARTER, SSHT_DL_QUARTER_EXTENDED, SSHT_DL_RISBO, SSHT_DL_TRAPANI, SSHT_ERROR_GENERIC, SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PION2, SSHT_PROMPT, ssht_sampling_elm2ind(), and ssht_sampling_weight_mw().
Referenced by main(), and ssht_core_mw_forward_sov_conv_sym_ss_real().
ssht_core_mw_lb_inverse_sov_sym()
void ssht_core_mw_lb_inverse_sov_sym (complex double * f, const complex double * flm, int L0, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
Compute inverse transform for MW method using separation of variables, fast Fourier transforms and exploiting all symmetries (for complex spin signal).
Parameters
[out] f Function on sphere.
[in] flm Harmonic coefficients.
[in] L0 Lower harmonic band-limit.
[in] L Upper harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 75 of file ssht_core.c.
References MAX, ssht_dl_beta_risbo_eighth_table(), ssht_dl_beta_risbo_fill_eighth2quarter_table(), ssht_dl_calloc(), ssht_dl_get_offset(), ssht_dl_get_stride(), ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), SSHT_DL_QUARTER, SSHT_DL_QUARTER_EXTENDED, SSHT_DL_RISBO, SSHT_DL_TRAPANI, SSHT_ERROR_GENERIC, SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PION2, and SSHT_PROMPT.
Referenced by main(), and ssht_core_mw_inverse_sov_sym().
ssht_core_mw_lb_inverse_sov_sym_real()
void ssht_core_mw_lb_inverse_sov_sym_real (double * f, const complex double * flm, int L0, int L, ssht_dl_method_t dl_method, int verbosity)
Compute inverse transform for MW method of real scalar signal using separation of variables, fast Fourier transforms and exploiting all symmetries (including additional symmetries for real signals).
Parameters
[out] f Function on sphere.
[in] flm Harmonic coefficients.
[in] L0 Lower harmonic band-limit.
[in] L Upper harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 346 of file ssht_core.c.
References MAX, ssht_dl_beta_risbo_eighth_table(), ssht_dl_beta_risbo_fill_eighth2quarter_table(), ssht_dl_calloc(), ssht_dl_get_offset(), ssht_dl_get_stride(), ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), SSHT_DL_QUARTER, SSHT_DL_QUARTER_EXTENDED, SSHT_DL_RISBO, SSHT_DL_TRAPANI, SSHT_ERROR_GENERIC, SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PION2, and SSHT_PROMPT.
Referenced by main(), and ssht_core_mw_inverse_sov_sym_real().
ssht_core_mw_lb_inverse_sov_sym_ss()
void ssht_core_mw_lb_inverse_sov_sym_ss (complex double * f, const complex double * flm, int L0, int L, int spin, ssht_dl_method_t dl_method, int verbosity)
Compute inverse transform for MW method with symmetric sampling using separation of variables, fast Fourier transforms and exploiting all symmetries (for complex spin signal).
Parameters
[out] f Function on sphere.
[in] flm Harmonic coefficients.
[in] L0 Lower harmonic band-limit.
[in] L Upper harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 1822 of file ssht_core.c.
References MAX, ssht_dl_beta_risbo_eighth_table(), ssht_dl_beta_risbo_fill_eighth2quarter_table(), ssht_dl_calloc(), ssht_dl_get_offset(), ssht_dl_get_stride(), ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), SSHT_DL_QUARTER, SSHT_DL_QUARTER_EXTENDED, SSHT_DL_RISBO, SSHT_DL_TRAPANI, SSHT_ERROR_GENERIC, SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PION2, and SSHT_PROMPT.
Referenced by main(), and ssht_core_mw_inverse_sov_sym_ss().
ssht_core_mw_lb_inverse_sov_sym_ss_real()
void ssht_core_mw_lb_inverse_sov_sym_ss_real (double * f, const complex double * flm, int L0, int L, ssht_dl_method_t dl_method, int verbosity)
Compute inverse transform for MW method with symmetric sampling of real scalar signal using separation of variables, fast Fourier transforms and exploiting all symmetries (including additional symmetries for real signals).
Parameters
[out] f Function on sphere.
[in] flm Harmonic coefficients.
[in] L0 Lower harmonic band-limit.
[in] L Upper harmonic band-limit.
[in] spin Spin number.
[in] dl_method Method to use when compute Wigner functions.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 2093 of file ssht_core.c.
References MAX, ssht_dl_beta_risbo_eighth_table(), ssht_dl_beta_risbo_fill_eighth2quarter_table(), ssht_dl_calloc(), ssht_dl_get_offset(), ssht_dl_get_stride(), ssht_dl_halfpi_trapani_eighth_table(), ssht_dl_halfpi_trapani_fill_eighth2quarter_table(), SSHT_DL_QUARTER, SSHT_DL_QUARTER_EXTENDED, SSHT_DL_RISBO, SSHT_DL_TRAPANI, SSHT_ERROR_GENERIC, SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PION2, and SSHT_PROMPT.
Referenced by main(), and ssht_core_mw_inverse_sov_sym_ss_real().
ssht_core_mwdirect_inverse()
void ssht_core_mwdirect_inverse (complex double * f, const complex double * flm, int L, int spin, int verbosity)
Compute inverse transform using direct method for MW sampling.
Warning
This algorithm is very slow and is included for verification purposes only.
Parameters
[out] f Function on sphere.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 587 of file ssht_core.c.
References ssht_dl_beta_risbo_full_table(), ssht_dl_calloc(), SSHT_DL_FULL, ssht_dl_get_offset(), ssht_dl_get_stride(), SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PROMPT, ssht_sampling_elm2ind(), ssht_sampling_mw_p2phi(), and ssht_sampling_mw_t2theta().
ssht_core_mwdirect_inverse_sov()
void ssht_core_mwdirect_inverse_sov (complex double * f, const complex double * flm, int L, int spin, int verbosity)
Compute inverse transform using direct method with separation of variables for MW sampling.
Warning
This algorithm is included for verification purposes only.
Parameters
[out] f Function on sphere.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 686 of file ssht_core.c.
References ssht_dl_beta_kostelec_line_table(), SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PROMPT, ssht_sampling_elm2ind(), and ssht_sampling_mw_t2theta().
ssht_core_mwdirect_inverse_ss()
void ssht_core_mwdirect_inverse_ss (complex double * f, const complex double * flm, int L, int spin, int verbosity)
Compute inverse transform using direct method for MW symmetric sampling.
Warning
This algorithm is very slow and is included for verification purposes only.
Parameters
[out] f Function on sphere.
[in] flm Harmonic coefficients.
[in] L Harmonic band-limit.
[in] spin Spin number.
[in] verbosity Verbosity flag in range [0,5].
Return values
none
Author
Jason McEwen
Definition at line 2325 of file ssht_core.c.
References ssht_dl_beta_risbo_full_table(), ssht_dl_calloc(), SSHT_DL_FULL, ssht_dl_get_offset(), ssht_dl_get_stride(), SSHT_ERROR_MEM_ALLOC_CHECK, SSHT_PI, SSHT_PROMPT, ssht_sampling_elm2ind(), ssht_sampling_mw_ss_p2phi(), and ssht_sampling_mw_ss_t2theta().