name: ci

on:
  push:
      branches: ["main"]
  pull_request:

jobs:
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Create wheel
      run: python setup.py bdist
    
    - name: Install Application
      run: pip install --user dist/pyssht*
      
    - name: Test with pytest
      run: |
          pip install pytest
          pytest src/pyssht/pyssht_test.py
