name: CMake

on:
  push:
      branches: ["main"]
  pull_request:

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create Build Environment
      shell: bash
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install conan ninja
        conan profile new default --detect
        cmake -E make_directory ${{runner.workspace}}/build

    - name: Install gcc on windows
      if: "${{matrix.os == 'windows-latest'}}"
      shell: powershell
      run: |
        iwr -useb get.scoop.sh | iex
        scoop install ninja
        scoop install gcc

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      run: cmake .. -DCMAKE_C_COMPILER=gcc -DCMAKE_BUILD_TYPE=$BUILD_TYPE -G Ninja -Dpython=False -Dconan_deps=True
    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest -C $BUILD_TYPE
