name: CMake Build

on:
  push:
    branches: ["main"]
  pull_request:

env:
  BUILD_TYPE: Debug

jobs:
  build:
    name: CMake build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: install conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Create Build Environment
        shell: bash
        run: |
          conan profile detect --force
          conan install . --build=missing --settings=build_type=${BUILD_TYPE}

      - name: Configure and build this project
        uses: threeal/cmake-action@latest
        with:
            args: '-DBUILD_TESTING=ON --preset=conan-${BUILD_TYPE,,}'
            run-test: true
