name: Python Build

on:
  push:
      branches: ["main"]
      tags:
        - 'v[0-9]+.[0-9]+.[0-9]+'
        - 'v[0-9]+.[0-9]+.[0-9]+rc[0-9]+'
  pull_request:

jobs:
    from-source:
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: false
          matrix:
            os: [ubuntu-latest, macos-latest]
            python-version: [3.8]

        steps:
        - uses: actions/checkout@v2
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install build packages and pytest
          run: python -m pip install --upgrade pip scikit-build pytest

        - name: Install pyssht
          run: pip install .
          
        - name: run pytest
          run: pytest tests/test_pyssht.py

    packaging:
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: false
          matrix:
            os: [ubuntu-latest, macos-latest]
            python-version: [3.8]

        steps:
        - uses: actions/checkout@v2
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install build packages and pytest
          run: |
              python -m pip install --upgrade pip wheel setuptools
              python -m pip install conan scikit-build pytest cython numpy

        - name: Create sdist package
          run: python setup.py sdist bdist_wheel

        - name: Install pyssht
          run: "pip install dist/pyssht-*.tar.gz"

        - name: run pytest
          run: pytest tests/test_pyssht.py

        - name: store wheels
          uses: actions/upload-artifact@v2
          with:
            name: pyssht-${{matrix.os}}
            path: dist/pyssht*.whl

        - name: store sdist
          if: matrix.os == 'ubuntu-latest'
          uses: actions/upload-artifact@v2
          with:
            name: pyssht-${{matrix.os}}
            path: dist/pyssht*.tar.gz

    publication:
        runs-on: ubuntu-latest
        needs: packaging
        steps:
        - name: Download wheels and sdist
          uses: actions/download-artifact@v2
        - name: move everything to dist
          run: |
              mkdir -p dist
              cp pyssht-*/* dist

        - name: Publish distribution 📦 to Test PyPI
          if: github.ref != 'refs/tags/v1.3.2'
          uses: pypa/gh-action-pypi-publish@master
          with:
            password: ${{ secrets.TEST_PYPI_TOKEN }}
            repository_url: https://test.pypi.org/legacy/

        - name: Publish distribution 📦 to PyPI
          if: github.ref == 'refs/tags/v1.3.2'
          uses: pypa/gh-action-pypi-publish@master
          with:
            password: ${{ secrets.PYPI_TOKEN }}
            repository_url: https://pypi.org/legacy/
