name: python

on:
  push:
      branches: ["main"]
  pull_request:

jobs:
    from-source:
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: false
          matrix:
            os: [ubuntu-latest, macos-latest]
            python-version: [3.8]

        steps:
        - uses: actions/checkout@v2
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        
        - name: Install build packages and pytest
          run: python -m pip install --upgrade pip scikit-build pytest

        - name: Install pyssht
          run: pip install .
          
        - name: run pytest
          run: pytest tests/test_pyssht.py

    packaging:
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: false
          matrix:
            os: [ubuntu-latest, macos-latest]
            python-version: [3.8]

        steps:
        - uses: actions/checkout@v2
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        
        - name: Install build packages and pytest
          run: python -m pip install --upgrade pip scikit-build pytest

        - name: Create sdist package
          run: python setup.py sdist

        - name: Install pyssht
          run: pip install dist/pyssht-1.3.2.tar.gz
          
        - name: run pytest
          run: pytest tests/test_pyssht.py
