name: windows

on:
  push:
      branches: ["main"]
  pull_request:

env:
  BUILD_TYPE: Debug
  CC: gcc

jobs:
  cmake-build:
    runs-on: windows-latest

    
    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: |
        iwr -useb get.scoop.sh | iex
        scoop install gcc

        python -m pip install --upgrade pip wheel
        python -m pip install conan ninja
        conan profile new default --detect

        cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -G Ninja -Dconan_deps=ON

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

  python-package:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    
    - name: Install build packages and pytest
      run: python -m pip install --upgrade pip scikit-build pytest

    - name: Create sdist package
      run: python setup.py sdist

    - name: Install pyssht
      run: pip install .
      
    - name: run pytest
      run: pytest tests/test_pyssht.py
